import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'package:aziz_academy/core/providers/coin_provider.dart';
import 'package:aziz_academy/core/router/app_router.dart';
import 'package:aziz_academy/core/theme/app_colors.dart';
import 'package:aziz_academy/core/theme/app_text_styles.dart';
import 'package:aziz_academy/core/utils/digits.dart';
import 'package:aziz_academy/core/l10n/context_ext.dart';

/// Maze Runner — swipe or tap arrows to navigate from green start
/// (top-left) to red goal (bottom-right). Maze is procedurally
/// generated by recursive backtracker. ١١×١١ default; ١٥×١٥ hard.
/// +٢🪙 first solve, +٥🪙 ≤ ٤٠ moves, +١٠🪙 ≤ ٢٥ moves.
class MazeRunnerScreen extends ConsumerStatefulWidget {
  const MazeRunnerScreen({super.key});

  @override
  ConsumerState<MazeRunnerScreen> createState() => _MazeRunnerScreenState();
}

class _Cell {
  bool top = true, right = true, bottom = true, left = true;
  bool visited = false;
}

class _MazeRunnerScreenState extends ConsumerState<MazeRunnerScreen> {
  int _size = 11;
  late List<List<_Cell>> _grid;
  int _px = 0, _py = 0;
  int _moves = 0;
  bool _won = false;
  bool _firstWin = false, _solved40 = false, _solved25 = false;

  @override
  void initState() {
    super.initState();
    _newMaze();
  }

  void _newMaze() {
    _grid = List<List<_Cell>>.generate(
      _size,
      (_) => List<_Cell>.generate(_size, (_) => _Cell()),
    );
    _carve(0, 0, math.Random());
    setState(() {
      _px = 0;
      _py = 0;
      _moves = 0;
      _won = false;
    });
  }

  void _carve(int x, int y, math.Random rng) {
    _grid[y][x].visited = true;
    final dirs = [0, 1, 2, 3]..shuffle(rng);
    for (final d in dirs) {
      final nx = x + [0, 1, 0, -1][d];
      final ny = y + [-1, 0, 1, 0][d];
      if (nx < 0 || ny < 0 || nx >= _size || ny >= _size) continue;
      if (_grid[ny][nx].visited) continue;
      switch (d) {
        case 0:
          _grid[y][x].top = false;
          _grid[ny][nx].bottom = false;
          break;
        case 1:
          _grid[y][x].right = false;
          _grid[ny][nx].left = false;
          break;
        case 2:
          _grid[y][x].bottom = false;
          _grid[ny][nx].top = false;
          break;
        case 3:
          _grid[y][x].left = false;
          _grid[ny][nx].right = false;
          break;
      }
      _carve(nx, ny, rng);
    }
  }

  bool _canMove(int dx, int dy) {
    final c = _grid[_py][_px];
    if (dx == 1) return !c.right;
    if (dx == -1) return !c.left;
    if (dy == 1) return !c.bottom;
    if (dy == -1) return !c.top;
    return false;
  }

  void _move(int dx, int dy) {
    if (_won) return;
    if (!_canMove(dx, dy)) return;
    HapticFeedback.selectionClick();
    setState(() {
      _px += dx;
      _py += dy;
      _moves += 1;
      if (_px == _size - 1 && _py == _size - 1) {
        _won = true;
        _award();
      }
    });
  }

  void _award() {
    HapticFeedback.heavyImpact();
    if (!_firstWin) {
      _firstWin = true;
      ref.read(coinProvider.notifier).award(2);
    }
    if (!_solved40 && _moves <= 40) {
      _solved40 = true;
      ref.read(coinProvider.notifier).award(5);
    }
    if (!_solved25 && _moves <= 25) {
      _solved25 = true;
      ref.read(coinProvider.notifier).award(10);
    }
  }

  @override
  Widget build(BuildContext context) {
    final isAr = Directionality.of(context) == TextDirection.rtl;
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.background,
        elevation: 0,
        leading: IconButton(
          tooltip: context.l10n.commonBack,
          icon: Icon(
            isAr ? Icons.arrow_forward : Icons.arrow_back,
            color: AppColors.textDark,
          ),
          onPressed: () {
            if (context.canPop()) {
              context.pop();
            } else {
              context.go(AppRoutes.home);
            }
          },
        ),
        title: Text(
          isAr ? 'متاهة' : 'Maze Runner',
          style: AppTextStyles.headingSmall,
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            tooltip: isAr ? 'متاهة جديدة' : 'New maze',
            onPressed: _newMaze,
          ),
        ],
      ),
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(12),
          child: Column(
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  _Pill(
                    label: isAr ? 'الحركات' : 'Moves',
                    value: localizeDigits(_moves, arabic: isAr),
                  ),
                  Wrap(
                    spacing: 6,
                    children: [
                      for (final s in [9, 11, 15])
                        ChoiceChip(
                          label: Text(
                            '${localizeDigits(s, arabic: isAr)}×${localizeDigits(s, arabic: isAr)}',
                          ),
                          selected: _size == s,
                          onSelected: (_) {
                            setState(() => _size = s);
                            _newMaze();
                          },
                        ),
                    ],
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Expanded(
                child: AspectRatio(
                  aspectRatio: 1,
                  child: GestureDetector(
                    onPanEnd: (d) {
                      final v = d.velocity.pixelsPerSecond;
                      if (v.dx.abs() > v.dy.abs()) {
                        if (v.dx > 80) _move(1, 0);
                        if (v.dx < -80) _move(-1, 0);
                      } else {
                        if (v.dy > 80) _move(0, 1);
                        if (v.dy < -80) _move(0, -1);
                      }
                    },
                    child: CustomPaint(
                      painter: _MazePainter(
                        grid: _grid,
                        size: _size,
                        px: _px,
                        py: _py,
                        wallColor: AppColors.textDark,
                        bgColor: AppColors.surfaceContainer,
                        playerColor: AppColors.primary,
                        startColor: AppColors.success,
                        goalColor: AppColors.error,
                      ),
                    ),
                  ),
                ),
              ),
              const SizedBox(height: 12),
              if (_won) ...[
                Text(
                  isAr
                      ? 'وصلت! ${localizeDigits(_moves, arabic: true)} حركة'
                      : 'Reached the goal! $_moves moves',
                  style: AppTextStyles.headingSmall.copyWith(
                    color: AppColors.success,
                  ),
                ),
                const SizedBox(height: 8),
                ElevatedButton.icon(
                  onPressed: _newMaze,
                  icon: const Icon(Icons.replay),
                  label: Text(isAr ? 'مرة أخرى' : 'Play again'),
                ),
              ] else
                Row(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    IconButton.filled(
                      onPressed: () => _move(0, -1),
                      icon: const Icon(Icons.arrow_upward),
                    ),
                    const SizedBox(width: 8),
                    IconButton.filled(
                      onPressed: () => _move(-1, 0),
                      icon: const Icon(Icons.arrow_back),
                    ),
                    const SizedBox(width: 8),
                    IconButton.filled(
                      onPressed: () => _move(0, 1),
                      icon: const Icon(Icons.arrow_downward),
                    ),
                    const SizedBox(width: 8),
                    IconButton.filled(
                      onPressed: () => _move(1, 0),
                      icon: const Icon(Icons.arrow_forward),
                    ),
                  ],
                ),
            ],
          ),
        ),
      ),
    );
  }
}

class _MazePainter extends CustomPainter {
  _MazePainter({
    required this.grid,
    required this.size,
    required this.px,
    required this.py,
    required this.wallColor,
    required this.bgColor,
    required this.playerColor,
    required this.startColor,
    required this.goalColor,
  });
  final List<List<_Cell>> grid;
  final int size;
  final int px, py;
  final Color wallColor, bgColor, playerColor, startColor, goalColor;

  @override
  void paint(Canvas canvas, Size cs) {
    final cell = cs.width / size;
    final bg = Paint()..color = bgColor;
    canvas.drawRect(Rect.fromLTWH(0, 0, cs.width, cs.height), bg);

    // Start & goal markers
    final start = Paint()..color = startColor.withValues(alpha: 0.3);
    canvas.drawRect(Rect.fromLTWH(0, 0, cell, cell), start);
    final goal = Paint()..color = goalColor.withValues(alpha: 0.4);
    canvas.drawRect(
      Rect.fromLTWH((size - 1) * cell, (size - 1) * cell, cell, cell),
      goal,
    );

    // Player
    final pPaint = Paint()..color = playerColor;
    canvas.drawCircle(
      Offset(px * cell + cell / 2, py * cell + cell / 2),
      cell * 0.32,
      pPaint,
    );

    // Walls
    final wall = Paint()
      ..color = wallColor
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke;
    for (var y = 0; y < size; y++) {
      for (var x = 0; x < size; x++) {
        final c = grid[y][x];
        final l = x * cell;
        final t = y * cell;
        final r = l + cell;
        final b = t + cell;
        if (c.top) canvas.drawLine(Offset(l, t), Offset(r, t), wall);
        if (c.right) canvas.drawLine(Offset(r, t), Offset(r, b), wall);
        if (c.bottom) canvas.drawLine(Offset(l, b), Offset(r, b), wall);
        if (c.left) canvas.drawLine(Offset(l, t), Offset(l, b), wall);
      }
    }
  }

  @override
  bool shouldRepaint(covariant _MazePainter old) =>
      old.px != px || old.py != py || old.size != size || old.grid != grid;
}

class _Pill extends StatelessWidget {
  const _Pill({required this.label, required this.value});
  final String label;
  final String value;
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 6),
      decoration: BoxDecoration(
        color: AppColors.surfaceContainer,
        borderRadius: BorderRadius.circular(999),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Text(label, style: AppTextStyles.labelSmall),
          const SizedBox(width: 6),
          Text(value, style: AppTextStyles.labelLarge),
        ],
      ),
    );
  }
}
