import 'package:flutter/material.dart';
import 'package:aziz_academy/core/theme/app_colors.dart';
import 'package:aziz_academy/core/router/app_router.dart';
import 'package:aziz_academy/core/models/recap_module.dart';

enum ActivityCategory {
  learn,
  words,
  math,
  brain,
  action,
  versus,
  islamic,
  tools,
}

extension ActivityCategoryX on ActivityCategory {
  String labelEn() {
    switch (this) {
      case ActivityCategory.learn:
        return 'Learn';
      case ActivityCategory.words:
        return 'Words';
      case ActivityCategory.math:
        return 'Math';
      case ActivityCategory.brain:
        return 'Brain';
      case ActivityCategory.action:
        return 'Action';
      case ActivityCategory.versus:
        return 'Versus';
      case ActivityCategory.islamic:
        return 'Islamic';
      case ActivityCategory.tools:
        return 'Tools';
    }
  }

  String labelAr() {
    switch (this) {
      case ActivityCategory.learn:
        return 'تعلَّم';
      case ActivityCategory.words:
        return 'كلمات';
      case ActivityCategory.math:
        return 'رياضيات';
      case ActivityCategory.brain:
        return 'ذكاء';
      case ActivityCategory.action:
        return 'تحدي';
      case ActivityCategory.versus:
        return 'لاعبان';
      case ActivityCategory.islamic:
        return 'إسلامي';
      case ActivityCategory.tools:
        return 'الأدوات';
    }
  }

  String emoji() {
    switch (this) {
      case ActivityCategory.learn:
        return '📚';
      case ActivityCategory.words:
        return '🔤';
      case ActivityCategory.math:
        return '🔢';
      case ActivityCategory.brain:
        return '🧠';
      case ActivityCategory.action:
        return '⚡';
      case ActivityCategory.versus:
        return '🤝';
      case ActivityCategory.islamic:
        return '🕌';
      case ActivityCategory.tools:
        return '⚙️';
    }
  }
}

/// A single activity in the smart home catalog.
/// `recapModule` is set only for the five spaced-repetition modules so the
/// home grid can surface their pending review counts.
class Activity {
  const Activity({
    required this.id,
    required this.titleEn,
    required this.titleAr,
    required this.subtitleEn,
    required this.subtitleAr,
    required this.emoji,
    required this.accent,
    required this.route,
    required this.category,
    this.recapModule,
    this.featured = false,
  });

  final String id;
  final String titleEn;
  final String titleAr;
  final String subtitleEn;
  final String subtitleAr;
  final String emoji;
  final Color accent;
  final String route;
  final ActivityCategory category;
  final RecapModule? recapModule;
  final bool featured;

  String title({required bool ar}) => ar ? titleAr : titleEn;
  String subtitle({required bool ar}) => ar ? subtitleAr : subtitleEn;

  bool matches(String query) {
    if (query.isEmpty) return true;
    final q = query.toLowerCase().trim();
    return titleEn.toLowerCase().contains(q) ||
        subtitleEn.toLowerCase().contains(q) ||
        titleAr.contains(q) ||
        subtitleAr.contains(q);
  }
}

const _learn = ActivityCategory.learn;
const _words = ActivityCategory.words;
const _math = ActivityCategory.math;
const _brain = ActivityCategory.brain;
const _action = ActivityCategory.action;
const _versus = ActivityCategory.versus;
const _islamic = ActivityCategory.islamic;
const _tools = ActivityCategory.tools;

const _purple = Color(0xFFC47AC0);
const _amber = Color(0xFFFFD166);
const _coral = Color(0xFFFF7B5C);
const _green = Color(0xFF6BBF59);
const _crimson = Color(0xFFB04B4B);
const _ocean = Color(0xFF42A5F5);
const _violet = Color(0xFF8E7CC3);
const _terracotta = Color(0xFFEC8A4A);
const _aqua = Color(0xFF26A69A);
const _orchid = Color(0xFFAB47BC);
const _grass = Color(0xFF66BB6A);
const _navy = Color(0xFF2C63B3);
const _royal = Color(0xFF6A1B9A);

/// Master list — everything reachable from home. Order ≈ recency / importance
/// inside each category so the grid feels well-curated.
const List<Activity> kActivities = [
  // ── LEARN ─────────────────────────────────────────────────────────────
  Activity(
    id: 'capitals',
    titleEn: 'Capitals',
    titleAr: 'العواصم',
    subtitleEn: 'Match countries to their capital cities',
    subtitleAr: 'طابق الدولة بعاصمتها',
    emoji: '🏛️',
    accent: AppColors.capitalsColor,
    route: AppRoutes.capitals,
    category: _learn,
    recapModule: RecapModule.capitals,
    featured: true,
  ),
  Activity(
    id: 'flags',
    titleEn: 'Flags',
    titleAr: 'الأعلام',
    subtitleEn: 'Spot the flag of every country',
    subtitleAr: 'تعرَّف على أعلام الدول',
    emoji: '🚩',
    accent: AppColors.error,
    route: AppRoutes.flags,
    category: _learn,
    recapModule: RecapModule.flags,
    featured: true,
  ),
  Activity(
    id: 'maps',
    titleEn: 'Maps',
    titleAr: 'الخرائط',
    subtitleEn: 'Find countries on the world map',
    subtitleAr: 'حدِّد الدول على الخريطة',
    emoji: '🗺️',
    accent: AppColors.mapsColor,
    route: AppRoutes.maps,
    category: _learn,
    recapModule: RecapModule.maps,
  ),
  Activity(
    id: 'logos',
    titleEn: 'Logos',
    titleAr: 'الشعارات',
    subtitleEn: 'Recognize famous brand logos',
    subtitleAr: 'تعرَّف على الشعارات الشهيرة',
    emoji: '🏷️',
    accent: AppColors.logosColor,
    route: AppRoutes.logos,
    category: _learn,
  ),
  Activity(
    id: 'sciences',
    titleEn: 'Sciences',
    titleAr: 'العلوم',
    subtitleEn: 'Discover how the world works',
    subtitleAr: 'اكتشف كيف يعمل العالم',
    emoji: '🔬',
    accent: _purple,
    route: AppRoutes.sciences,
    category: _learn,
    recapModule: RecapModule.sciences,
    featured: true,
  ),
  Activity(
    id: 'math',
    titleEn: 'Math',
    titleAr: 'الرياضيات',
    subtitleEn: 'Practice numbers, sums, and more',
    subtitleAr: 'تمارين الأعداد والحساب',
    emoji: '🔢',
    accent: _navy,
    route: AppRoutes.math,
    category: _math,
    recapModule: RecapModule.math,
    featured: true,
  ),
  Activity(
    id: 'iq',
    titleEn: 'IQ Challenge',
    titleAr: 'تحدي الذكاء',
    subtitleEn: 'Logic, patterns, brain workouts',
    subtitleAr: 'منطق وأنماط وتمارين ذهنية',
    emoji: '🧠',
    accent: _purple,
    route: AppRoutes.iq,
    category: _learn,
    featured: true,
  ),
  Activity(
    id: 'general_quiz',
    titleEn: 'General Quiz',
    titleAr: 'ثقافة عامة',
    subtitleEn: 'A little of everything',
    subtitleAr: 'أسئلة من كل المجالات',
    emoji: '🌍',
    accent: _amber,
    route: AppRoutes.generalQuizIntro,
    category: _learn,
    featured: true,
  ),
  Activity(
    id: 'blitz',
    titleEn: 'Blitz Round',
    titleAr: 'الجولة الخاطفة',
    subtitleEn: '60 seconds, every module',
    subtitleAr: '٦٠ ثانية من كل المواضيع',
    emoji: '⚡',
    accent: _coral,
    route: AppRoutes.blitz,
    category: _learn,
    featured: true,
  ),
  Activity(
    id: 'survival',
    titleEn: 'Survival',
    titleAr: 'البقاء',
    subtitleEn: 'How long can you keep streaking?',
    subtitleAr: 'استمر دون إجابة خاطئة',
    emoji: '🛡️',
    accent: _green,
    route: AppRoutes.survival,
    category: _learn,
  ),
  Activity(
    id: 'boss',
    titleEn: 'Boss Battle',
    titleAr: 'معركة الزعيم',
    subtitleEn: 'Defeat the toughest questions',
    subtitleAr: 'تحدَّ الأسئلة الأصعب',
    emoji: '👹',
    accent: _crimson,
    route: AppRoutes.boss,
    category: _learn,
  ),
  Activity(
    id: 'true_false',
    titleEn: 'True / False',
    titleAr: 'صح أم خطأ',
    subtitleEn: 'Quick yes-or-no rounds',
    subtitleAr: 'جولات سريعة نعم أو لا',
    emoji: '✅',
    accent: _green,
    route: AppRoutes.trueFalse,
    category: _learn,
  ),
  Activity(
    id: 'self_challenge',
    titleEn: 'Self Challenge',
    titleAr: 'تحدّ نفسك',
    subtitleEn: 'Build your own round',
    subtitleAr: 'صمِّم جولتك الخاصة',
    emoji: '🎯',
    accent: _ocean,
    route: AppRoutes.selfChallenge,
    category: _learn,
  ),
  Activity(
    id: 'random_quiz',
    titleEn: 'Random Quiz',
    titleAr: 'اختبار عشوائي',
    subtitleEn: 'A surprise mix from every topic',
    subtitleAr: 'مزيج مفاجئ من كل المواد',
    emoji: '🎲',
    accent: _orchid,
    route: AppRoutes.randomQuiz,
    category: _learn,
  ),
  Activity(
    id: 'boss_rush',
    titleEn: 'Boss Rush',
    titleAr: 'هجوم الزعماء',
    subtitleEn: '12 questions, 3 modules in a row',
    subtitleAr: '١٢ سؤالًا من ٣ مواد',
    emoji: '🐉',
    accent: _crimson,
    route: AppRoutes.bossRush,
    category: _learn,
  ),
  Activity(
    id: 'learning_zone',
    titleEn: 'Reading Zone',
    titleAr: 'ركن القراءة',
    subtitleEn: 'Read a story, answer questions',
    subtitleAr: 'اقرأ قصة وأجب عن الأسئلة',
    emoji: '📖',
    accent: _violet,
    route: AppRoutes.learningZone,
    category: _learn,
    featured: true,
  ),
  Activity(
    id: 'vocab_flashcards',
    titleEn: 'Flashcards',
    titleAr: 'البطاقات',
    subtitleEn: 'Vocabulary, fast and fun',
    subtitleAr: 'حفظ المفردات بسرعة',
    emoji: '🗂️',
    accent: _aqua,
    route: AppRoutes.vocabFlashcards,
    category: _learn,
  ),
  Activity(
    id: 'smart_quiz',
    titleEn: 'Smart Quiz',
    titleAr: 'الاختبار الذكي',
    subtitleEn: 'Adapts to what you need most',
    subtitleAr: 'يتكيَّف مع ما تحتاجه',
    emoji: '🎯',
    accent: AppColors.primary,
    route: AppRoutes.smartQuiz,
    category: _learn,
  ),
  Activity(
    id: 'homework',
    titleEn: 'Homework Helper',
    titleAr: 'مساعد الواجب',
    subtitleEn: 'Study mode — answers shown',
    subtitleAr: 'وضع الدراسة مع الإجابات',
    emoji: '📚',
    accent: _grass,
    route: AppRoutes.homeworkHelper,
    category: _learn,
  ),
  Activity(
    id: 'weekly_tourney',
    titleEn: 'Weekly Tournament',
    titleAr: 'بطولة الأسبوع',
    subtitleEn: 'One best score each week',
    subtitleAr: 'أفضل نتيجة في الأسبوع',
    emoji: '🏆',
    accent: _amber,
    route: AppRoutes.weeklyTourney,
    category: _learn,
  ),

  // ── WORDS ─────────────────────────────────────────────────────────────
  Activity(
    id: 'spelling',
    titleEn: 'Spelling',
    titleAr: 'الإملاء',
    subtitleEn: 'Build the word letter by letter',
    subtitleAr: 'كوِّن الكلمة حرفًا بحرف',
    emoji: '🅰️',
    accent: _terracotta,
    route: AppRoutes.spelling,
    category: _words,
    featured: true,
  ),
  Activity(
    id: 'hangman',
    titleEn: 'Hangman',
    titleAr: 'الحبل',
    subtitleEn: 'Guess the secret word',
    subtitleAr: 'خمِّن الكلمة المخفية',
    emoji: '🪢',
    accent: _terracotta,
    route: AppRoutes.hangman,
    category: _words,
  ),
  Activity(
    id: 'anagram',
    titleEn: 'Anagram',
    titleAr: 'كلمات مبعثرة',
    subtitleEn: 'Rearrange the letters',
    subtitleAr: 'رتِّب الحروف لتكوين كلمة',
    emoji: '🔣',
    accent: _amber,
    route: AppRoutes.anagram,
    category: _words,
  ),
  Activity(
    id: 'word_scramble',
    titleEn: 'Word Scramble',
    titleAr: 'خلط الكلمات',
    subtitleEn: 'Unscramble the word, fast',
    subtitleAr: 'رتِّب الحروف بسرعة',
    emoji: '🪄',
    accent: _violet,
    route: AppRoutes.wordScramble,
    category: _words,
  ),
  Activity(
    id: 'word_search',
    titleEn: 'Word Search',
    titleAr: 'بحث الكلمات',
    subtitleEn: 'Find words hidden in a grid',
    subtitleAr: 'ابحث عن الكلمات في الشبكة',
    emoji: '🔡',
    accent: _aqua,
    route: AppRoutes.wordSearch,
    category: _words,
  ),
  Activity(
    id: 'crossword',
    titleEn: 'Crossword',
    titleAr: 'الكلمات المتقاطعة',
    subtitleEn: 'Across, down — fill the grid',
    subtitleAr: 'املأ شبكة الكلمات',
    emoji: '🧩',
    accent: _ocean,
    route: AppRoutes.crossword,
    category: _words,
  ),
  Activity(
    id: 'tap_letter',
    titleEn: 'Tap the Letter',
    titleAr: 'اضغط الحرف',
    subtitleEn: 'Find the requested letter fast',
    subtitleAr: 'اعثر على الحرف بسرعة',
    emoji: '🆎',
    accent: _coral,
    route: AppRoutes.tapLetter,
    category: _words,
  ),
  Activity(
    id: 'speed_reading',
    titleEn: 'Speed Reading',
    titleAr: 'القراءة السريعة',
    subtitleEn: 'Train how fast you read',
    subtitleAr: 'درِّب سرعة قراءتك',
    emoji: '⚡',
    accent: _coral,
    route: AppRoutes.speedReading,
    category: _words,
  ),
  Activity(
    id: 'alphabet',
    titleEn: 'Arabic Alphabet',
    titleAr: 'الحروف العربية',
    subtitleEn: 'Letters, sounds, and shapes',
    subtitleAr: 'الحروف وأشكالها وأصواتها',
    emoji: '🔤',
    accent: _amber,
    route: AppRoutes.alphabet,
    category: _words,
  ),
  Activity(
    id: 'english-alphabet',
    titleEn: 'English Alphabet',
    titleAr: 'الحروف الإنجليزية',
    subtitleEn: 'A to Z with words & emojis',
    subtitleAr: 'الحروف الست والعشرون مع كلمات ورموز',
    emoji: '🔤',
    accent: _ocean,
    route: AppRoutes.englishAlphabet,
    category: _words,
  ),
  Activity(
    id: 'type_answer',
    titleEn: 'Type the Answer',
    titleAr: 'اكتب الإجابة',
    subtitleEn: 'Type your reply, no choices',
    subtitleAr: 'اكتب الجواب بدون خيارات',
    emoji: '⌨️',
    accent: _aqua,
    route: AppRoutes.typeAnswer,
    category: _words,
  ),

  // ── MATH ──────────────────────────────────────────────────────────────
  Activity(
    id: 'times_tables',
    titleEn: 'Times Tables',
    titleAr: 'جدول الضرب',
    subtitleEn: 'Master multiplication',
    subtitleAr: 'احفظ جدول الضرب',
    emoji: '✖️',
    accent: _navy,
    route: AppRoutes.timesTables,
    category: _math,
    featured: true,
  ),
  Activity(
    id: 'number-bonds',
    titleEn: 'Number Bonds',
    titleAr: 'روابط الأعداد',
    subtitleEn: 'Make 10 and 20',
    subtitleAr: 'أكمل الـ ١٠ والـ ٢٠',
    emoji: '🧮',
    accent: _grass,
    route: AppRoutes.numberBonds,
    category: _math,
  ),
  Activity(
    id: 'shapes-basics',
    titleEn: 'Shapes Basics',
    titleAr: 'الأشكال',
    subtitleEn: '12 shapes — names & sides',
    subtitleAr: 'اثنا عشر شكلًا — أسماء وأضلاع',
    emoji: '🔷',
    accent: _violet,
    route: AppRoutes.shapesBasics,
    category: _math,
  ),
  Activity(
    id: 'place-value',
    titleEn: 'Place Value',
    titleAr: 'المنازل العشرية',
    subtitleEn: 'Tens and ones blocks',
    subtitleAr: 'مكعبات العشرات والآحاد',
    emoji: '🔢',
    accent: _ocean,
    route: AppRoutes.placeValue,
    category: _math,
  ),
  Activity(
    id: 'skip-counting',
    titleEn: 'Skip Counting',
    titleAr: 'العد بالقفز',
    subtitleEn: 'Count by 2s, 5s, 10s',
    subtitleAr: 'العد بـ ٢ و ٥ و ١٠',
    emoji: '⏭️',
    accent: _terracotta,
    route: AppRoutes.skipCounting,
    category: _math,
  ),
  Activity(
    id: 'math_sprint',
    titleEn: 'Math Sprint',
    titleAr: 'سباق الحساب',
    subtitleEn: 'Solve as many as you can',
    subtitleAr: 'حل أكبر عدد ممكن',
    emoji: '➕',
    accent: _navy,
    route: AppRoutes.mathSprint,
    category: _math,
  ),
  Activity(
    id: 'speed_math',
    titleEn: 'Speed Math',
    titleAr: 'الحساب السريع',
    subtitleEn: 'Beat the clock with answers',
    subtitleAr: 'أجب قبل انتهاء الوقت',
    emoji: '📐',
    accent: _ocean,
    route: AppRoutes.speedMath,
    category: _math,
  ),
  Activity(
    id: 'multiplication_practice',
    titleEn: 'Times Tables',
    titleAr: 'جدول الضرب',
    subtitleEn: 'Practice ×2 through ×12 with accuracy tracking',
    subtitleAr: 'تدرب على الجداول مع تتبع الدقة',
    emoji: '✖️',
    accent: _navy,
    route: AppRoutes.multiplicationPractice,
    category: _math,
  ),
  Activity(
    id: 'mental_math_sprint',
    titleEn: 'Mental Math Sprint',
    titleAr: 'الحساب الذهني',
    subtitleEn: '60-second drill — beat your best',
    subtitleAr: 'تحدي ٦٠ ثانية — اكسر رقمك القياسي',
    emoji: '⚡',
    accent: _ocean,
    route: AppRoutes.mentalMathSprint,
    category: _math,
  ),
  Activity(
    id: 'fractions_practice',
    titleEn: 'Fractions',
    titleAr: 'الكسور',
    subtitleEn: 'Identify and compare with visuals',
    subtitleAr: 'حدد وقارن الكسور بالصور',
    emoji: '🥧',
    accent: _navy,
    route: AppRoutes.fractionsPractice,
    category: _math,
  ),
  Activity(
    id: 'prime_tap',
    titleEn: 'Prime Tap',
    titleAr: 'الأعداد الأولية',
    subtitleEn: 'Tap only the prime numbers',
    subtitleAr: 'اضغط الأعداد الأولية فقط',
    emoji: '➗',
    accent: _navy,
    route: AppRoutes.primeTap,
    category: _math,
  ),
  Activity(
    id: 'even_odd',
    titleEn: 'Even or Odd',
    titleAr: 'زوجي أم فردي',
    subtitleEn: 'Sort numbers by parity',
    subtitleAr: 'صنِّف الأعداد حسب نوعها',
    emoji: '↔️',
    accent: _ocean,
    route: AppRoutes.evenOdd,
    category: _math,
  ),
  Activity(
    id: 'roman',
    titleEn: 'Roman Numerals',
    titleAr: 'الأرقام الرومانية',
    subtitleEn: 'Convert between systems',
    subtitleAr: 'حوِّل بين الأنظمة الرقمية',
    emoji: '📜',
    accent: _terracotta,
    route: AppRoutes.romanNumerals,
    category: _math,
  ),
  Activity(
    id: 'fraction_match',
    titleEn: 'Fraction Match',
    titleAr: 'مطابقة الكسور',
    subtitleEn: 'Match the equal fractions',
    subtitleAr: 'طابق الكسور المتساوية',
    emoji: '🥧',
    accent: _coral,
    route: AppRoutes.fractionMatch,
    category: _math,
  ),
  Activity(
    id: 'greater_than',
    titleEn: 'Greater Than',
    titleAr: 'أكبر من',
    subtitleEn: 'Compare two numbers fast',
    subtitleAr: 'قارن العددين بسرعة',
    emoji: '⚖️',
    accent: _ocean,
    route: AppRoutes.greaterThan,
    category: _math,
  ),
  Activity(
    id: 'sum_hunt',
    titleEn: 'Sum Hunt',
    titleAr: 'صيد المجموع',
    subtitleEn: 'Tap pairs that add up',
    subtitleAr: 'اضغط الأزواج التي مجموعها صحيح',
    emoji: '🟰',
    accent: _navy,
    route: AppRoutes.sumHunt,
    category: _math,
  ),
  Activity(
    id: 'number_memory',
    titleEn: 'Number Memory',
    titleAr: 'ذاكرة الأرقام',
    subtitleEn: 'How long a number can you remember?',
    subtitleAr: 'كم رقمًا تستطيع تذكره؟',
    emoji: '🧮',
    accent: _purple,
    route: AppRoutes.numberMemory,
    category: _math,
  ),
  Activity(
    id: 'counting_stars',
    titleEn: 'Counting Stars',
    titleAr: 'عدّ النجوم',
    subtitleEn: 'Count, tap, and learn',
    subtitleAr: 'عدّ النجوم بسرعة',
    emoji: '⭐',
    accent: _amber,
    route: AppRoutes.countingStars,
    category: _math,
  ),
  Activity(
    id: '2048',
    titleEn: '2048',
    titleAr: '٢٠٤٨',
    subtitleEn: 'Slide tiles, double up',
    subtitleAr: 'اجمع المربعات لتصل إلى ٢٠٤٨',
    emoji: '🔟',
    accent: _amber,
    route: AppRoutes.twoThousand,
    category: _math,
  ),
  Activity(
    id: 'clock_read',
    titleEn: 'Read the Clock',
    titleAr: 'قراءة الساعة',
    subtitleEn: 'Tell the time at a glance',
    subtitleAr: 'تعلَّم قراءة الساعة',
    emoji: '🕒',
    accent: _navy,
    route: AppRoutes.clockRead,
    category: _math,
  ),
  Activity(
    id: '15_puzzle',
    titleEn: '15 Puzzle',
    titleAr: 'لغز الـ١٥',
    subtitleEn: 'Slide tiles into order',
    subtitleAr: 'رتِّب المربعات بالتمرير',
    emoji: '🔢',
    accent: _navy,
    route: AppRoutes.fifteenPuzzle,
    category: _math,
  ),
  Activity(
    id: 'tap_greatest',
    titleEn: 'Tap the Greatest',
    titleAr: 'اضغط الأكبر',
    subtitleEn: 'Find the biggest number',
    subtitleAr: 'اعثر على العدد الأكبر',
    emoji: '🔝',
    accent: _coral,
    route: AppRoutes.tapGreatest,
    category: _math,
  ),

  // ── BRAIN ─────────────────────────────────────────────────────────────
  Activity(
    id: 'sudoku',
    titleEn: 'Sudoku',
    titleAr: 'سودوكو',
    subtitleEn: 'Classic 9x9 number puzzle',
    subtitleAr: 'لغز الأرقام الكلاسيكي',
    emoji: '🔢',
    accent: _purple,
    route: AppRoutes.sudoku,
    category: _brain,
    featured: true,
  ),
  Activity(
    id: 'hanoi',
    titleEn: 'Tower of Hanoi',
    titleAr: 'برج هانوي',
    subtitleEn: 'Move the disks, mind the rules',
    subtitleAr: 'انقل الأقراص باتباع القواعد',
    emoji: '🗼',
    accent: _amber,
    route: AppRoutes.hanoi,
    category: _brain,
  ),
  Activity(
    id: 'mastermind',
    titleEn: 'Mastermind',
    titleAr: 'العقل المدبِّر',
    subtitleEn: 'Crack the secret code',
    subtitleAr: 'اكتشف الرمز السري',
    emoji: '🎯',
    accent: _ocean,
    route: AppRoutes.mastermind,
    category: _brain,
  ),
  Activity(
    id: 'lights_out',
    titleEn: 'Lights Out',
    titleAr: 'إطفاء الأضواء',
    subtitleEn: 'Turn off every light',
    subtitleAr: 'اطفئ كل الأضواء',
    emoji: '💡',
    accent: _amber,
    route: AppRoutes.lightsOut,
    category: _brain,
  ),
  Activity(
    id: 'memory_match',
    titleEn: 'Memory Match',
    titleAr: 'طابق الذاكرة',
    subtitleEn: 'Match every pair of cards',
    subtitleAr: 'طابق كل أزواج البطاقات',
    emoji: '🃏',
    accent: _orchid,
    route: AppRoutes.memoryMatch,
    category: _brain,
    featured: true,
  ),
  Activity(
    id: 'schulte',
    titleEn: 'Schulte Table',
    titleAr: 'جدول شولت',
    subtitleEn: 'Train peripheral vision',
    subtitleAr: 'درِّب الرؤية المحيطية',
    emoji: '👁',
    accent: _aqua,
    route: AppRoutes.schulte,
    category: _brain,
  ),
  Activity(
    id: 'stroop',
    titleEn: 'Stroop',
    titleAr: 'ستروب',
    subtitleEn: 'Mind says color, eyes say word',
    subtitleAr: 'لون أم كلمة؟',
    emoji: '🌈',
    accent: _orchid,
    route: AppRoutes.stroop,
    category: _brain,
  ),
  Activity(
    id: 'pattern_next',
    titleEn: 'Next Pattern',
    titleAr: 'النمط التالي',
    subtitleEn: 'What comes next in the sequence?',
    subtitleAr: 'ما الذي يأتي بعد ذلك؟',
    emoji: '📈',
    accent: _violet,
    route: AppRoutes.patternNext,
    category: _brain,
  ),
  Activity(
    id: 'find_twin',
    titleEn: 'Find the Twin',
    titleAr: 'اعثر على التوأم',
    subtitleEn: 'Spot the matching pair',
    subtitleAr: 'اعثر على الزوج المتطابق',
    emoji: '👯',
    accent: _aqua,
    route: AppRoutes.findTwin,
    category: _brain,
  ),
  Activity(
    id: 'odd_one_out',
    titleEn: 'Odd One Out',
    titleAr: 'الشاذ من بينها',
    subtitleEn: 'Pick the one that does not belong',
    subtitleAr: 'اختر العنصر الشاذ',
    emoji: '🔍',
    accent: _coral,
    route: AppRoutes.oddOneOut,
    category: _brain,
  ),
  Activity(
    id: 'odd_color',
    titleEn: 'Odd Color',
    titleAr: 'اللون المختلف',
    subtitleEn: 'Find the slightly different square',
    subtitleAr: 'اعثر على المربع المختلف',
    emoji: '🟪',
    accent: _orchid,
    route: AppRoutes.oddColor,
    category: _brain,
  ),
  Activity(
    id: 'shape_match',
    titleEn: 'Shape Match',
    titleAr: 'مطابقة الأشكال',
    subtitleEn: 'Match shapes by family',
    subtitleAr: 'طابق الأشكال المتشابهة',
    emoji: '🔷',
    accent: _ocean,
    route: AppRoutes.shapeMatch,
    category: _brain,
  ),
  Activity(
    id: 'maze_runner',
    titleEn: 'Maze Runner',
    titleAr: 'متاهة',
    subtitleEn: 'Find the way out',
    subtitleAr: 'اعثر على المخرج',
    emoji: '🌀',
    accent: _purple,
    route: AppRoutes.mazeRunner,
    category: _brain,
  ),
  Activity(
    id: 'sokoban',
    titleEn: 'Sokoban',
    titleAr: 'سوكوبان',
    subtitleEn: 'Push the boxes onto goals',
    subtitleAr: 'ادفع الصناديق إلى أماكنها',
    emoji: '📦',
    accent: _terracotta,
    route: AppRoutes.sokoban,
    category: _brain,
  ),
  Activity(
    id: 'lemonade',
    titleEn: 'Lemonade Stand',
    titleAr: 'كشك الليمون',
    subtitleEn: 'Run a daily lemonade business',
    subtitleAr: 'أدر مشروع عصير الليمون',
    emoji: '🍋',
    accent: _amber,
    route: AppRoutes.lemonadeStand,
    category: _brain,
  ),
  Activity(
    id: 'higher_lower',
    titleEn: 'Higher or Lower',
    titleAr: 'أعلى أم أقل',
    subtitleEn: 'Guess if next card is higher',
    subtitleAr: 'خمِّن إذا كانت الورقة التالية أكبر',
    emoji: '🎴',
    accent: _green,
    route: AppRoutes.higherLower,
    category: _brain,
  ),
  Activity(
    id: 'pegs',
    titleEn: 'Peg Solitaire',
    titleAr: 'سوليتير الأوتاد',
    subtitleEn: 'Hop pegs to clear the board',
    subtitleAr: 'انقل الأوتاد لتفريغ اللوحة',
    emoji: '🟡',
    accent: _amber,
    route: AppRoutes.pegs,
    category: _brain,
  ),
  Activity(
    id: 'tap_sequence',
    titleEn: 'Tap Sequence',
    titleAr: 'تتابع الضغط',
    subtitleEn: 'Tap numbers in order',
    subtitleAr: 'اضغط الأرقام بالترتيب',
    emoji: '🆗',
    accent: _ocean,
    route: AppRoutes.tapSequence,
    category: _brain,
  ),

  // ── ACTION ────────────────────────────────────────────────────────────
  Activity(
    id: 'snake',
    titleEn: 'Snake',
    titleAr: 'الأفعى',
    subtitleEn: 'Eat, grow, do not bite yourself',
    subtitleAr: 'كل وانمُ بدون أن تلدغ نفسك',
    emoji: '🐍',
    accent: _green,
    route: AppRoutes.snake,
    category: _action,
  ),
  Activity(
    id: 'tetris_lite',
    titleEn: 'Block Drop',
    titleAr: 'إسقاط القطع',
    subtitleEn: 'Stack blocks, clear lines',
    subtitleAr: 'كدِّس القطع وامسح الصفوف',
    emoji: '🧊',
    accent: _ocean,
    route: AppRoutes.tetrisLite,
    category: _action,
  ),
  Activity(
    id: 'brick_breaker',
    titleEn: 'Brick Breaker',
    titleAr: 'كسر الطوب',
    subtitleEn: 'Bounce, break, clear the wall',
    subtitleAr: 'حطِّم كل الطوب',
    emoji: '🧱',
    accent: _coral,
    route: AppRoutes.brickBreaker,
    category: _action,
  ),
  Activity(
    id: 'pong',
    titleEn: 'Pong',
    titleAr: 'بونغ',
    subtitleEn: 'Classic paddle bounce',
    subtitleAr: 'مضرب وكرة',
    emoji: '🏓',
    accent: _aqua,
    route: AppRoutes.pong,
    category: _action,
  ),
  Activity(
    id: 'bowling',
    titleEn: 'Bowling',
    titleAr: 'البولينغ',
    subtitleEn: 'Knock down all the pins',
    subtitleAr: 'أسقط كل الأوتاد',
    emoji: '🎳',
    accent: _terracotta,
    route: AppRoutes.bowling,
    category: _action,
  ),
  Activity(
    id: 'balloon_pop',
    titleEn: 'Balloon Pop',
    titleAr: 'فقع البالون',
    subtitleEn: 'Pop balloons, dodge bombs',
    subtitleAr: 'افقع البالونات وتجنّب القنابل',
    emoji: '🎈',
    accent: _coral,
    route: AppRoutes.balloonPop,
    category: _action,
  ),
  Activity(
    id: 'bubble_pop',
    titleEn: 'Bubble Pop',
    titleAr: 'فقاعات',
    subtitleEn: 'Pop bubbles before they escape',
    subtitleAr: 'افقع الفقاعات قبل أن تهرب',
    emoji: '🫧',
    accent: _ocean,
    route: AppRoutes.bubblePop,
    category: _action,
  ),
  Activity(
    id: 'fruit_catcher',
    titleEn: 'Fruit Catcher',
    titleAr: 'صياد الفاكهة',
    subtitleEn: 'Catch the falling fruit',
    subtitleAr: 'امسك الفاكهة المتساقطة',
    emoji: '🍎',
    accent: _crimson,
    route: AppRoutes.fruitCatcher,
    category: _action,
  ),
  Activity(
    id: 'hoop_shot',
    titleEn: 'Hoop Shot',
    titleAr: 'رمية السلة',
    subtitleEn: 'Aim, throw, score',
    subtitleAr: 'صوِّب وارمِ وسجِّل',
    emoji: '🏀',
    accent: _terracotta,
    route: AppRoutes.hoopShot,
    category: _action,
  ),
  Activity(
    id: 'beat_tap',
    titleEn: 'Beat Tap',
    titleAr: 'إيقاع الضغط',
    subtitleEn: 'Tap to the rhythm',
    subtitleAr: 'اضغط على الإيقاع',
    emoji: '🎵',
    accent: _orchid,
    route: AppRoutes.beatTap,
    category: _action,
  ),
  Activity(
    id: 'reaction_time',
    titleEn: 'Reaction Time',
    titleAr: 'سرعة البديهة',
    subtitleEn: 'Tap the moment it turns green',
    subtitleAr: 'اضغط فور تحول اللون',
    emoji: '⚡',
    accent: _coral,
    route: AppRoutes.reactionTime,
    category: _action,
  ),
  Activity(
    id: 'whack_a_mole',
    titleEn: 'Whack-a-Mole',
    titleAr: 'صيد الخلد',
    subtitleEn: 'Whack the moles, fast',
    subtitleAr: 'اطرق الخلد بسرعة',
    emoji: '🦫',
    accent: _terracotta,
    route: AppRoutes.whackAMole,
    category: _action,
  ),
  Activity(
    id: 'simon_says',
    titleEn: 'Simon Says',
    titleAr: 'سيمون يقول',
    subtitleEn: 'Repeat the colors in order',
    subtitleAr: 'كرِّر الألوان بالترتيب',
    emoji: '🟥',
    accent: _crimson,
    route: AppRoutes.simonSays,
    category: _action,
  ),
  Activity(
    id: 'tap_jump',
    titleEn: 'Tap Jump',
    titleAr: 'القفز',
    subtitleEn: 'Jump over obstacles',
    subtitleAr: 'اقفز فوق العقبات',
    emoji: '🦘',
    accent: _green,
    route: AppRoutes.tapJump,
    category: _action,
  ),
  Activity(
    id: 'asteroid_dodge',
    titleEn: 'Asteroid Dodge',
    titleAr: 'مراوغة الكويكبات',
    subtitleEn: 'Dodge the falling rocks',
    subtitleAr: 'تجنّب الكويكبات',
    emoji: '☄️',
    accent: _purple,
    route: AppRoutes.asteroidDodge,
    category: _action,
  ),
  Activity(
    id: 'crossy_lane',
    titleEn: 'Crossy Lane',
    titleAr: 'عبور الشارع',
    subtitleEn: 'Cross every lane safely',
    subtitleAr: 'اعبر الطريق بأمان',
    emoji: '🐔',
    accent: _amber,
    route: AppRoutes.crossyLane,
    category: _action,
  ),
  Activity(
    id: 'stick_hero',
    titleEn: 'Stick Hero',
    titleAr: 'بطل العصا',
    subtitleEn: 'Stretch the stick — just right',
    subtitleAr: 'مدّ العصا بالطول الصحيح',
    emoji: '🌉',
    accent: _violet,
    route: AppRoutes.stickHero,
    category: _action,
  ),
  Activity(
    id: 'stack_builder',
    titleEn: 'Stack Builder',
    titleAr: 'بناء البرج',
    subtitleEn: 'Stack blocks as high as you can',
    subtitleAr: 'كدِّس المكعبات لأعلى ارتفاع',
    emoji: '🏗️',
    accent: _terracotta,
    route: AppRoutes.stackBuilder,
    category: _action,
  ),
  Activity(
    id: 'penalty',
    titleEn: 'Penalty Shootout',
    titleAr: 'ركلات الترجيح',
    subtitleEn: 'Score from the spot',
    subtitleAr: 'سدِّد من نقطة الجزاء',
    emoji: '⚽',
    accent: _green,
    route: AppRoutes.penaltyShootout,
    category: _action,
  ),
  Activity(
    id: 'cup_shuffle',
    titleEn: 'Cup Shuffle',
    titleAr: 'خلط الأكواب',
    subtitleEn: 'Track the cup with the ball',
    subtitleAr: 'تتبَّع الكوب الذي تحته الكرة',
    emoji: '🥤',
    accent: _ocean,
    route: AppRoutes.cupShuffle,
    category: _action,
  ),
  Activity(
    id: 'match_three',
    titleEn: 'Match 3',
    titleAr: 'مطابقة الثلاثة',
    subtitleEn: 'Match three jewels in a row',
    subtitleAr: 'طابق ٣ جواهر متشابهة',
    emoji: '💎',
    accent: _orchid,
    route: AppRoutes.matchThree,
    category: _action,
  ),
  Activity(
    id: 'color_match',
    titleEn: 'Color Match',
    titleAr: 'مطابقة الألوان',
    subtitleEn: 'Tap the right color quickly',
    subtitleAr: 'اضغط اللون الصحيح بسرعة',
    emoji: '🎨',
    accent: _crimson,
    route: AppRoutes.colorMatch,
    category: _action,
  ),
  Activity(
    id: 'color_mix',
    titleEn: 'Color Mix',
    titleAr: 'مزج الألوان',
    subtitleEn: 'Mix to match the target',
    subtitleAr: 'اخلط الألوان لمطابقة الهدف',
    emoji: '🎀',
    accent: _orchid,
    route: AppRoutes.colorMix,
    category: _action,
  ),

  // ── VERSUS ────────────────────────────────────────────────────────────
  Activity(
    id: 'tic_tac_toe',
    titleEn: 'Tic-Tac-Toe',
    titleAr: 'إكس أو',
    subtitleEn: 'Three in a row to win',
    subtitleAr: 'ثلاثة في صف للفوز',
    emoji: '❌',
    accent: _ocean,
    route: AppRoutes.ticTacToe,
    category: _versus,
  ),
  Activity(
    id: 'connect_four',
    titleEn: 'Connect 4',
    titleAr: 'أربعة في صف',
    subtitleEn: 'Four in a row, any direction',
    subtitleAr: 'أربعة على التوالي بأي اتجاه',
    emoji: '🔴',
    accent: _crimson,
    route: AppRoutes.connectFour,
    category: _versus,
  ),
  Activity(
    id: 'reversi',
    titleEn: 'Reversi',
    titleAr: 'ريفرسي',
    subtitleEn: 'Flip the board, own the most',
    subtitleAr: 'اقلب الأقراص ليكون لك العدد الأكبر',
    emoji: '⚫',
    accent: _navy,
    route: AppRoutes.reversi,
    category: _versus,
  ),
  Activity(
    id: 'dots_boxes',
    titleEn: 'Dots & Boxes',
    titleAr: 'النقاط والمربعات',
    subtitleEn: 'Close more boxes than your rival',
    subtitleAr: 'أغلق مربعات أكثر من خصمك',
    emoji: '🟦',
    accent: _ocean,
    route: AppRoutes.dotsBoxes,
    category: _versus,
  ),
  Activity(
    id: 'battleship',
    titleEn: 'Battleship',
    titleAr: 'حرب السفن',
    subtitleEn: 'Sink the enemy fleet',
    subtitleAr: 'أغرق سفن العدو',
    emoji: '🚢',
    accent: _navy,
    route: AppRoutes.battleship,
    category: _versus,
  ),
  Activity(
    id: 'pig_dice',
    titleEn: 'Pig Dice',
    titleAr: 'لعبة النرد',
    subtitleEn: 'Roll, bank, win to 100',
    subtitleAr: 'ارمِ النرد واصل إلى ١٠٠',
    emoji: '🐷',
    accent: _coral,
    route: AppRoutes.pigDice,
    category: _versus,
  ),
  Activity(
    id: 'pass_play',
    titleEn: 'Pass & Play',
    titleAr: 'مرِّر والعب',
    subtitleEn: '2 players on one device',
    subtitleAr: 'لاعبان على جهاز واحد',
    emoji: '🤝',
    accent: _ocean,
    route: AppRoutes.passPlay,
    category: _versus,
  ),

  // ── ISLAMIC ───────────────────────────────────────────────────────────
  // Ordered by learning flow: sacred texts → personal worship → deeds → study.
  Activity(
    id: 'quran',
    titleEn: 'Quran',
    titleAr: 'القرآن',
    subtitleEn: 'Read, listen, memorize',
    subtitleAr: 'اقرأ واستمع واحفظ',
    emoji: '📖',
    accent: _amber,
    route: AppRoutes.quran,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'hadith',
    titleEn: 'Hadith Memorization',
    titleAr: 'حفظ الأحاديث',
    subtitleEn: 'Short authentic hadiths for kids',
    subtitleAr: 'أحاديث قصيرة صحيحة للأطفال',
    emoji: '📜',
    accent: AppColors.secondary,
    route: AppRoutes.hadithMemorization,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'asma_ul_husna',
    titleEn: '99 Names of Allah',
    titleAr: 'أسماء الله الحسنى',
    subtitleEn: 'Learn the beautiful names',
    subtitleAr: 'تعلَّم الأسماء الحسنى',
    emoji: '☪️',
    accent: _amber,
    route: AppRoutes.asmaUlHusna,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'prophet_stories',
    titleEn: 'Prophet Stories',
    titleAr: 'قصص الأنبياء',
    subtitleEn: 'The 25 prophets, kid-friendly',
    subtitleAr: 'قصص الأنبياء الـ٢٥ للأطفال',
    emoji: '📿',
    accent: AppColors.secondary,
    route: AppRoutes.prophetStories,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'dua',
    titleEn: 'Dua Memorization',
    titleAr: 'حفظ الأدعية',
    subtitleEn: 'Learn duas line by line',
    subtitleAr: 'احفظ الأدعية سطرًا سطرًا',
    emoji: '🤲',
    accent: _amber,
    route: AppRoutes.duaMemorization,
    category: _islamic,
  ),
  Activity(
    id: 'athkar',
    titleEn: 'Athkar',
    titleAr: 'الأذكار',
    subtitleEn: 'Morning and evening reminders',
    subtitleAr: 'أذكار الصباح والمساء',
    emoji: '📿',
    accent: AppColors.secondary,
    route: AppRoutes.athkar,
    category: _islamic,
  ),
  Activity(
    id: 'tasbih',
    titleEn: 'Tasbih',
    titleAr: 'التسبيح',
    subtitleEn: 'Digital prayer beads',
    subtitleAr: 'مسبحة رقمية',
    emoji: '🧿',
    accent: _violet,
    route: AppRoutes.tasbih,
    category: _islamic,
  ),
  Activity(
    id: 'prayer',
    titleEn: 'Prayer Times',
    titleAr: 'مواقيت الصلاة',
    subtitleEn: 'Today\'s prayer schedule',
    subtitleAr: 'مواقيت الصلاة اليوم',
    emoji: '🕌',
    accent: AppColors.secondary,
    route: AppRoutes.prayerTimes,
    category: _islamic,
  ),
  Activity(
    id: 'five_pillars',
    titleEn: 'Five Pillars',
    titleAr: 'أركان الإسلام',
    subtitleEn: 'The foundations of Islam',
    subtitleAr: 'أسس الإسلام الخمسة',
    emoji: '🕌',
    accent: AppColors.secondary,
    route: AppRoutes.fivePillars,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'six_articles',
    titleEn: 'Six Articles of Faith',
    titleAr: 'أركان الإيمان',
    subtitleEn: 'What every Muslim believes',
    subtitleAr: 'ما يؤمن به كل مسلم',
    emoji: '☪️',
    accent: _amber,
    route: AppRoutes.sixArticles,
    category: _islamic,
  ),
  Activity(
    id: 'islamic_journey',
    titleEn: 'My Islamic Journey',
    titleAr: 'رحلتي الإسلامية',
    subtitleEn: 'Track your progress',
    subtitleAr: 'تابع تقدمك',
    emoji: '🌟',
    accent: AppColors.secondary,
    route: AppRoutes.islamicJourney,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'asma_ul_husna_quiz',
    titleEn: '99 Names Quiz',
    titleAr: 'اختبار الأسماء الحسنى',
    subtitleEn: 'Test your recall — 10 names',
    subtitleAr: 'اختبر معرفتك — ١٠ أسماء',
    emoji: '🎯',
    accent: _amber,
    route: AppRoutes.asmaUlHusnaQuiz,
    category: _islamic,
  ),
  Activity(
    id: 'hadith_quiz',
    titleEn: 'Hadith Quiz',
    titleAr: 'اختبار الأحاديث',
    subtitleEn: 'Match the hadith to its meaning',
    subtitleAr: 'اختر معنى الحديث',
    emoji: '📜',
    accent: AppColors.accent,
    route: AppRoutes.hadithQuiz,
    category: _islamic,
  ),
  Activity(
    id: 'prophet_quiz',
    titleEn: 'Prophet Quiz',
    titleAr: 'اختبار الأنبياء',
    subtitleEn: 'Match the lesson to the prophet',
    subtitleAr: 'اختر النبي صاحب العبرة',
    emoji: '📿',
    accent: AppColors.success,
    route: AppRoutes.prophetQuiz,
    category: _islamic,
  ),
  Activity(
    id: 'islamic_search',
    titleEn: 'Islamic Search',
    titleAr: 'بحث إسلامي',
    subtitleEn: 'Find hadiths, names, prophets, duas',
    subtitleAr: 'ابحث في الأحاديث والأسماء والأنبياء والأدعية',
    emoji: '🔍',
    accent: AppColors.secondary,
    route: AppRoutes.islamicSearch,
    category: _islamic,
  ),
  Activity(
    id: 'tajweed_basics',
    titleEn: 'Tajweed Basics',
    titleAr: 'أساسيات التجويد',
    subtitleEn: '10 rules for beautiful recitation',
    subtitleAr: '١٠ قواعد لتلاوة جميلة',
    emoji: '📖',
    accent: AppColors.primary,
    route: AppRoutes.tajweedBasics,
    category: _islamic,
  ),
  Activity(
    id: 'daily_wisdom_quiz',
    titleEn: 'Daily Wisdom',
    titleAr: 'سؤال اليوم',
    subtitleEn: 'One new question every day',
    subtitleAr: 'سؤال جديد كل يوم',
    emoji: '🌟',
    accent: AppColors.accent,
    route: AppRoutes.dailyWisdomQuiz,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'salah_steps',
    titleEn: 'How to Pray',
    titleAr: 'كيف نصلي',
    subtitleEn: 'Step-by-step Salah guide',
    subtitleAr: 'تعلم الصلاة خطوة بخطوة',
    emoji: '🤲',
    accent: AppColors.secondary,
    route: AppRoutes.salahSteps,
    category: _islamic,
    featured: true,
  ),
  Activity(
    id: 'wudu_steps',
    titleEn: 'How to do Wudu',
    titleAr: 'الوضوء',
    subtitleEn: 'Step-by-step ablution guide',
    subtitleAr: 'تعلم الوضوء خطوة بخطوة',
    emoji: '💧',
    accent: AppColors.secondary,
    route: AppRoutes.wuduSteps,
    category: _islamic,
  ),
  Activity(
    id: 'sadaqah',
    titleEn: 'Sadaqah Jar',
    titleAr: 'برطمان الصدقة',
    subtitleEn: 'Track your daily good deeds',
    subtitleAr: 'سجِّل الصدقات اليومية',
    emoji: '🫙',
    accent: _green,
    route: AppRoutes.sadaqahJar,
    category: _islamic,
  ),
  Activity(
    id: 'madrasati',
    titleEn: 'Madrasati',
    titleAr: 'مدرستي',
    subtitleEn: 'School curriculum',
    subtitleAr: 'مناهج المدرسة',
    emoji: '🏫',
    accent: _royal,
    route: AppRoutes.madrasati,
    category: _islamic,
    featured: true,
  ),

  // ── TOOLS ─────────────────────────────────────────────────────────────
  Activity(
    id: 'shop',
    titleEn: 'Shop',
    titleAr: 'المتجر',
    subtitleEn: 'Spend coins on goodies',
    subtitleAr: 'اشترِ بالعملات الذهبية',
    emoji: '🛒',
    accent: _amber,
    route: AppRoutes.shop,
    category: _tools,
  ),
  Activity(
    id: 'treasure',
    titleEn: 'Treasure Room',
    titleAr: 'غرفة الكنز',
    subtitleEn: 'Open chests, claim rewards',
    subtitleAr: 'افتح الصناديق واحصل على جوائز',
    emoji: '🎁',
    accent: _amber,
    route: AppRoutes.treasure,
    category: _tools,
  ),
  Activity(
    id: 'hijri_converter',
    titleEn: 'Hijri Converter',
    titleAr: 'محول التاريخ',
    subtitleEn: 'Gregorian ↔ Islamic calendar',
    subtitleAr: 'ميلادي ↔ هجري',
    emoji: '🌙',
    accent: AppColors.secondary,
    route: AppRoutes.hijriConverter,
    category: _tools,
  ),
  Activity(
    id: 'leaderboard',
    titleEn: 'Best Scores',
    titleAr: 'أفضل النتائج',
    subtitleEn: 'My weekly + all-time records',
    subtitleAr: 'أفضل علاماتي الأسبوعية',
    emoji: '🏅',
    accent: _amber,
    route: AppRoutes.leaderboard,
    category: _tools,
  ),
  Activity(
    id: 'stats',
    titleEn: 'My Stats',
    titleAr: 'إحصائياتي',
    subtitleEn: 'Track your progress',
    subtitleAr: 'تابع تقدُّمك',
    emoji: '📊',
    accent: _ocean,
    route: AppRoutes.stats,
    category: _tools,
  ),
  Activity(
    id: 'parent',
    titleEn: 'Parent Area',
    titleAr: 'ركن الوالدين',
    subtitleEn: 'Reports and controls',
    subtitleAr: 'تقارير وإعدادات',
    emoji: '👨‍👩‍👧',
    accent: _violet,
    route: AppRoutes.parent,
    category: _tools,
  ),
  Activity(
    id: 'favorites',
    titleEn: 'Favorites',
    titleAr: 'المفضلة',
    subtitleEn: 'Your saved questions',
    subtitleAr: 'أسئلتك المحفوظة',
    emoji: '❤️',
    accent: AppColors.error,
    route: AppRoutes.favorites,
    category: _tools,
  ),
  // The Profile hub. Family profiles and profile editing are reached from
  // inside it (not as separate grid tiles), so a child has one clear "me".
  Activity(
    id: 'edit_profile',
    titleEn: 'My Profile',
    titleAr: 'ملفي',
    subtitleEn: 'Card, activity & siblings',
    subtitleAr: 'البطاقة والنشاط والإخوة',
    emoji: '🪪',
    accent: _ocean,
    route: AppRoutes.profileCard,
    category: _tools,
  ),
];

List<Activity> activitiesByCategory(ActivityCategory category) =>
    kActivities.where((a) => a.category == category).toList();

List<Activity> filterActivities({
  ActivityCategory? category,
  String query = '',
}) {
  Iterable<Activity> base = kActivities;
  if (category != null) {
    base = base.where((a) => a.category == category);
  }
  if (query.isNotEmpty) {
    base = base.where((a) => a.matches(query));
  }
  return base.toList();
}

Activity? activityById(String id) {
  for (final a in kActivities) {
    if (a.id == id) return a;
  }
  return null;
}
