#!/usr/bin/env python3
"""Generate antarctic_explorers.json (60 bilingual quiz items for kids 8-12)."""
from __future__ import annotations
import json, re
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "assets" / "data" / "antarctic_explorers.json"

# Western -> Arabic-Indic digits.
W2A = str.maketrans("0123456789", "٠١٢٣٤٥٦٧٨٩")

def ar(s: str) -> str:
    """Convert any Western digits in an Arabic string to Arabic-Indic."""
    return s.translate(W2A)

# Each entry: (id_num, difficulty, q_en, q_ar, [opt0_en, opt1_en, opt2_en, opt3_en],
#              [opt0_ar, opt1_ar, opt2_ar, opt3_ar], expl_en, expl_ar)
RAW = [
    # ---- EASY (22) ----
    (1, "easy",
     "Who was the first person to reach the South Pole?",
     "من أول شخص وصل إلى القطب الجنوبي؟",
     ["Roald Amundsen", "Robert Falcon Scott", "Ernest Shackleton", "Richard Byrd"],
     ["روال أموندسن", "روبرت فالكون سكوت", "إرنست شاكلتون", "ريتشارد بيرد"],
     "Norwegian explorer Roald Amundsen reached the South Pole on December 14, 1911 — about 5 weeks before Scott.",
     "وصل المستكشف النرويجي روال أموندسن إلى القطب الجنوبي في ١٤ ديسمبر ١٩١١ — قبل سكوت بنحو ٥ أسابيع."),
    (2, "easy",
     "From which country was Roald Amundsen?",
     "من أي بلد كان روال أموندسن؟",
     ["Norway", "Sweden", "Denmark", "Finland"],
     ["النرويج", "السويد", "الدنمارك", "فنلندا"],
     "Amundsen was Norwegian and grew up in a country with long, cold winters — perfect training for polar travel.",
     "كان أموندسن نرويجيًا ونشأ في بلد ذي شتاء طويل وبارد — تدريب مثالي للسفر القطبي."),
    (3, "easy",
     "Which continent is the South Pole on?",
     "في أي قارة يقع القطب الجنوبي؟",
     ["Antarctica", "Africa", "Australia", "South America"],
     ["القارة القطبية الجنوبية", "أفريقيا", "أستراليا", "أمريكا الجنوبية"],
     "Antarctica is the icy continent at the bottom of the world that surrounds the South Pole.",
     "القارة القطبية الجنوبية هي القارة الجليدية في أسفل العالم وتحيط بالقطب الجنوبي."),
    (4, "easy",
     "What is Antarctica almost completely covered by?",
     "بماذا تُغطى القارة القطبية الجنوبية تقريبًا بالكامل؟",
     ["Ice", "Sand", "Forest", "Grass"],
     ["الجليد", "الرمل", "الغابة", "العشب"],
     "About 98% of Antarctica is covered by a thick sheet of ice — in some places more than 4 km deep!",
     "نحو ٩٨٪ من القارة القطبية الجنوبية مُغطى بطبقة جليد سميكة — يصل عمقها في بعض الأماكن إلى أكثر من ٤ كم!"),
    (5, "easy",
     "Which of these animals lives in Antarctica?",
     "أيٌّ من هذه الحيوانات يعيش في القارة القطبية الجنوبية؟",
     ["Penguin", "Polar bear", "Camel", "Tiger"],
     ["البطريق", "الدب القطبي", "الجمل", "النمر"],
     "Penguins live in the southern hemisphere — polar bears live only in the Arctic, far away in the north.",
     "تعيش طيور البطريق في نصف الكرة الجنوبي — أما الدب القطبي فيعيش فقط في القطب الشمالي بعيدًا في الشمال."),
    (6, "easy",
     "What was the name of Shackleton's famous ship that got stuck in the ice?",
     "ما اسم سفينة شاكلتون الشهيرة التي علقت في الجليد؟",
     ["Endurance", "Titanic", "Beagle", "Mayflower"],
     ["إندورانس", "تيتانيك", "بيغل", "مايفلاور"],
     "The Endurance was crushed by pack ice in 1915, but all 28 men in the expedition survived!",
     "تحطّمت سفينة إندورانس بفعل جليد البحر عام ١٩١٥، لكن كل أفراد البعثة الـ ٢٨ نجوا!"),
    (7, "easy",
     "Which ocean surrounds Antarctica?",
     "أي محيط يحيط بالقارة القطبية الجنوبية؟",
     ["Southern Ocean", "Indian Ocean", "Arctic Ocean", "Mediterranean Sea"],
     ["المحيط الجنوبي", "المحيط الهندي", "المحيط المتجمد الشمالي", "البحر الأبيض المتوسط"],
     "The Southern Ocean (also called the Antarctic Ocean) wraps around the whole continent.",
     "يلتف المحيط الجنوبي (الذي يُسمى أيضًا المحيط المتجمد الجنوبي) حول القارة بأكملها."),
    (8, "easy",
     "Which continent is the COLDEST on Earth?",
     "أي قارة هي الأبرد على الأرض؟",
     ["Antarctica", "Asia", "Europe", "North America"],
     ["القارة القطبية الجنوبية", "آسيا", "أوروبا", "أمريكا الشمالية"],
     "Antarctica is the coldest, driest, and windiest continent on Earth.",
     "القارة القطبية الجنوبية هي الأبرد والأكثر جفافًا والأشد رياحًا على الأرض."),
    (9, "easy",
     "What was Shackleton's expedition trying to do?",
     "ماذا كانت بعثة شاكلتون تحاول أن تفعل؟",
     ["Cross Antarctica on foot", "Find gold", "Hunt whales", "Build a city"],
     ["عبور القارة القطبية الجنوبية سيرًا", "البحث عن الذهب", "صيد الحيتان", "بناء مدينة"],
     "Shackleton's 1914 plan was to cross all of Antarctica by foot, but his ship got trapped first!",
     "خطّط شاكلتون عام ١٩١٤ لعبور القارة القطبية الجنوبية كلها سيرًا، لكن سفينته حُوصرت أولًا!"),
    (10, "easy",
     "Who climbed Mount Everest in 1953 AND helped cross Antarctica in 1958?",
     "من تسلّق جبل إفرست عام ١٩٥٣ وساعد في عبور القارة القطبية الجنوبية عام ١٩٥٨؟",
     ["Edmund Hillary", "Roald Amundsen", "Captain Cook", "Robert Peary"],
     ["إدموند هيلاري", "روال أموندسن", "الكابتن كوك", "روبرت بيري"],
     "New Zealander Edmund Hillary led the New Zealand side of the first overland Antarctic crossing.",
     "قاد النيوزيلندي إدموند هيلاري الجانب النيوزيلندي من أول عبور بري للقارة القطبية الجنوبية."),
    (11, "easy",
     "What kind of bird is found ONLY in the Southern Hemisphere?",
     "أي طائر يُوجد فقط في نصف الكرة الجنوبي؟",
     ["Penguin", "Eagle", "Owl", "Parrot"],
     ["البطريق", "النسر", "البومة", "الببغاء"],
     "All 18 penguin species live south of the equator — they don't live near the North Pole!",
     "تعيش جميع أنواع البطريق الـ ١٨ جنوب خط الاستواء — ولا تعيش قرب القطب الشمالي!"),
    (12, "easy",
     "Which is the LARGEST type of penguin?",
     "ما أكبر أنواع البطريق؟",
     ["Emperor penguin", "Adélie penguin", "Chinstrap penguin", "Gentoo penguin"],
     ["البطريق الإمبراطور", "بطريق أديلي", "البطريق ذو الذقن", "البطريق الجنتو"],
     "Emperor penguins can grow over 1.2 meters tall — about as tall as a 7-year-old child!",
     "يصل طول البطريق الإمبراطور إلى أكثر من ١٫٢ متر — تقريبًا بطول طفل عمره ٧ سنوات!"),
    (13, "easy",
     "What is Antarctica's main color from space?",
     "ما اللون الرئيسي للقارة القطبية الجنوبية من الفضاء؟",
     ["White", "Green", "Brown", "Blue"],
     ["أبيض", "أخضر", "بني", "أزرق"],
     "Because almost everything is covered in ice and snow, Antarctica looks like a giant white shape from space.",
     "بما أن كل شيء تقريبًا مُغطى بالجليد والثلج، تبدو القارة القطبية الجنوبية ككتلة بيضاء عملاقة من الفضاء."),
    (14, "easy",
     "Does any single country OWN Antarctica?",
     "هل تملك أي دولة بمفردها القارة القطبية الجنوبية؟",
     ["No country owns it", "The USA owns it", "Russia owns it", "Norway owns it"],
     ["لا تملكها أي دولة", "تملكها الولايات المتحدة", "تملكها روسيا", "تملكها النرويج"],
     "Antarctica belongs to no country. Many nations share it for peaceful science under the Antarctic Treaty.",
     "لا تنتمي القارة القطبية الجنوبية إلى أي دولة. تتشاركها دول كثيرة في العلوم السلمية بموجب معاهدة أنتاركتيكا."),
    (15, "easy",
     "What is Antarctica mostly used for today?",
     "فيمَ تُستخدم القارة القطبية الجنوبية في معظمها اليوم؟",
     ["Science research", "Farming", "Big cities", "Theme parks"],
     ["الأبحاث العلمية", "الزراعة", "المدن الكبيرة", "ملاهي الترفيه"],
     "Antarctica is set aside as a continent for peaceful science — no farming, no armies, no mining.",
     "تُخصَّص القارة القطبية الجنوبية كقارة للعلوم السلمية — لا زراعة ولا جيوش ولا تعدين."),
    (16, "easy",
     "Which is the world's biggest source of fresh water (frozen)?",
     "أين يوجد أكبر مصدر للمياه العذبة في العالم (متجمدة)؟",
     ["Antarctic ice", "Lake Baikal", "Amazon river", "Niagara Falls"],
     ["جليد القارة القطبية الجنوبية", "بحيرة بايكال", "نهر الأمازون", "شلالات نياجرا"],
     "About 70% of all the fresh water on Earth is locked up in Antarctic ice!",
     "نحو ٧٠٪ من إجمالي المياه العذبة على الأرض محبوسة في جليد القارة القطبية الجنوبية!"),
    (17, "easy",
     "How long is the polar night (no sunlight) at the South Pole?",
     "كم تستمر الليلة القطبية (دون شمس) في القطب الجنوبي؟",
     ["About 6 months", "About 1 week", "About 1 day", "About 2 hours"],
     ["نحو ٦ أشهر", "نحو أسبوع", "نحو يوم واحد", "نحو ساعتين"],
     "At the poles the sun stays up for ~6 months and then sets for ~6 months. Long, dark winters!",
     "في القطبين تبقى الشمس مرتفعة نحو ٦ أشهر ثم تغيب نحو ٦ أشهر. شتاء طويل ومظلم!"),
    (18, "easy",
     "Which ocean is around the NORTH Pole?",
     "أي محيط يحيط بالقطب الشمالي؟",
     ["Arctic Ocean", "Atlantic Ocean", "Pacific Ocean", "Southern Ocean"],
     ["المحيط المتجمد الشمالي", "المحيط الأطلسي", "المحيط الهادئ", "المحيط الجنوبي"],
     "The Arctic isn't a continent — it's a frozen ocean surrounded by land.",
     "القطب الشمالي ليس قارة — بل محيط متجمد تحيط به اليابسة."),
    (19, "easy",
     "Which large animal hunts seals near the Antarctic ice?",
     "أي حيوان كبير يصطاد الفقمات قرب جليد القارة القطبية الجنوبية؟",
     ["Orca (killer whale)", "Lion", "Crocodile", "Giraffe"],
     ["الأوركا (الحوت القاتل)", "الأسد", "التمساح", "الزرافة"],
     "Orcas are top predators in Antarctic waters and sometimes work in teams to catch seals.",
     "الأوركا من أكبر المفترسات في مياه القارة القطبية الجنوبية وأحيانًا تعمل بفِرَق لاصطياد الفقمات."),
    (20, "easy",
     "What kind of clothing did early Antarctic explorers depend on?",
     "على أي نوع من الملابس اعتمد المستكشفون الأوائل للقارة القطبية الجنوبية؟",
     ["Fur and wool layers", "T-shirts", "Cotton shorts", "Sandals"],
     ["طبقات من الفراء والصوف", "قمصان قصيرة", "شورتات قطنية", "صنادل"],
     "They wore fur (often reindeer or seal) and wool inside, learning from Inuit Arctic peoples.",
     "ارتدوا الفراء (غالبًا فراء الرنة أو الفقمة) والصوف من الداخل، متعلمين من شعوب الإنويت في القطب الشمالي."),
    (21, "easy",
     "Which of these is a famous SLED animal in polar travel?",
     "أيٌّ من هذه حيوانات شهيرة لجر الزلاجات في السفر القطبي؟",
     ["Husky dog", "Camel", "Donkey", "Llama"],
     ["كلب الهاسكي", "الجمل", "الحمار", "اللاما"],
     "Husky-type dogs were used by Amundsen and many polar explorers to pull heavy sleds.",
     "استخدم أموندسن ومستكشفون قطبيون كثر كلاب الهاسكي لجر الزلاجات الثقيلة."),
    (22, "easy",
     "What is a 'glacier'?",
     "ما هو 'النهر الجليدي'؟",
     ["A huge slow-moving river of ice", "A frozen lake", "A snowman", "An iceberg in the sea"],
     ["نهر هائل من الجليد يتحرك ببطء", "بحيرة متجمدة", "رجل ثلج", "جبل جليدي في البحر"],
     "A glacier is ice that flows slowly downhill under its own weight, like a frozen river.",
     "النهر الجليدي هو جليد يتدفق ببطء إلى الأسفل تحت ثقله، مثل نهر متجمد."),

    # ---- MEDIUM (24) ----
    (23, "medium",
     "In what YEAR did Amundsen reach the South Pole?",
     "في أي عام وصل أموندسن إلى القطب الجنوبي؟",
     ["1911", "1820", "1953", "1969"],
     [ar("1911"), ar("1820"), ar("1953"), ar("1969")],
     "Amundsen's team reached the pole on December 14, 1911 — they planted the Norwegian flag there.",
     "وصل فريق أموندسن إلى القطب في ١٤ ديسمبر ١٩١١ — وزرعوا العلم النرويجي هناك."),
    (24, "medium",
     "How many weeks AFTER Amundsen did Scott reach the South Pole?",
     "بعد كم أسبوعًا من أموندسن وصل سكوت إلى القطب الجنوبي؟",
     ["About 5 weeks", "About 1 day", "About 6 months", "About 2 years"],
     ["نحو ٥ أسابيع", "نحو يوم واحد", "نحو ٦ أشهر", "نحو سنتين"],
     "Scott arrived January 17, 1912 and was heartbroken to find Amundsen's flag already planted.",
     "وصل سكوت في ١٧ يناير ١٩١٢ وانفطر قلبه حين وجد علم أموندسن مزروعًا هناك من قبل."),
    (25, "medium",
     "What tragedy happened to Scott's team after reaching the Pole?",
     "ما المأساة التي حلّت بفريق سكوت بعد وصوله إلى القطب؟",
     ["They died on the return journey", "They were captured by enemies", "They got rich", "They never reached the pole"],
     ["ماتوا في رحلة العودة", "أسرهم الأعداء", "أصبحوا أثرياء", "لم يصلوا إلى القطب أبدًا"],
     "Scott and his last 4 men died from cold and hunger in March 1912, only ~17 km from a supply depot.",
     "مات سكوت ورفاقه الأربعة الأخيرون من البرد والجوع في مارس ١٩١٢، على بُعد نحو ١٧ كم فقط من مخزن إمدادات."),
    (26, "medium",
     "What was the small lifeboat Shackleton sailed 800 miles in?",
     "ما اسم القارب الصغير الذي أبحر فيه شاكلتون مسافة ٨٠٠ ميل؟",
     ["James Caird", "Endurance", "Mayflower", "Beagle"],
     ["جيمس كيرد", "إندورانس", "مايفلاور", "بيغل"],
     "The James Caird was only 22 feet (7m) long — yet it crossed open Antarctic seas to South Georgia.",
     "كان طول جيمس كيرد ٢٢ قدمًا فقط (٧ أمتار) — ومع ذلك عَبَر بحارًا مفتوحة في القارة القطبية الجنوبية إلى جورجيا الجنوبية."),
    (27, "medium",
     "Who navigated the James Caird through huge waves using a sextant?",
     "من قاد القارب جيمس كيرد عبر الأمواج العاتية باستخدام السدس؟",
     ["Frank Worsley", "Roald Amundsen", "Tom Crean", "Frank Wild"],
     ["فرانك ورزلي", "روال أموندسن", "توم كرين", "فرانك وايلد"],
     "Captain Frank Worsley took only 4 sun-sights in 16 days yet found tiny South Georgia perfectly!",
     "أخذ القبطان فرانك ورزلي ٤ قياسات شمسية فقط خلال ١٦ يومًا ومع ذلك وجد جزيرة جورجيا الجنوبية الصغيرة بدقة!"),
    (28, "medium",
     "When was the wreck of the Endurance finally found?",
     "متى عُثر على حطام سفينة إندورانس أخيرًا؟",
     ["2022", "1985", "1955", "2002"],
     [ar("2022"), ar("1985"), ar("1955"), ar("2002")],
     "Searchers found the Endurance in March 2022 — about 3,000m deep in the Weddell Sea, 107 years later!",
     "عثر الباحثون على سفينة إندورانس في مارس ٢٠٢٢ — على عمق نحو ٣٠٠٠ متر في بحر ويدل، بعد ١٠٧ سنوات!"),
    (29, "medium",
     "Who claimed to be the first to reach the NORTH Pole in 1909?",
     "من ادّعى أنه أول من وصل إلى القطب الشمالي عام ١٩٠٩؟",
     ["Robert Peary", "Roald Amundsen", "Edmund Hillary", "James Cook"],
     ["روبرت بيري", "روال أموندسن", "إدموند هيلاري", "جيمس كوك"],
     "American Robert Peary said he reached the North Pole on April 6, 1909, but his claim is still disputed.",
     "قال الأمريكي روبرت بيري إنه وصل إلى القطب الشمالي في ٦ أبريل ١٩٠٩، لكن ادعاءه ما زال محل جدل."),
    (30, "medium",
     "Which African American explorer accompanied Peary on his Arctic trips?",
     "أي مستكشف أمريكي من أصل أفريقي رافق بيري في رحلاته القطبية الشمالية؟",
     ["Matthew Henson", "Frederick Cook", "Lincoln Ellsworth", "Tom Crean"],
     ["ماثيو هينسون", "فريدريك كوك", "لينكولن إلسوورث", "توم كرين"],
     "Matthew Henson was a skilled Arctic traveler and likely the first African American to reach the North Pole region.",
     "كان ماثيو هينسون رحالة قطبيًا ماهرًا، ومن المرجّح أنه أول أمريكي من أصل أفريقي يصل إلى منطقة القطب الشمالي."),
    (31, "medium",
     "Which OTHER American also claimed to reach the North Pole, in 1908?",
     "أي أمريكي آخر ادّعى أيضًا الوصول إلى القطب الشمالي عام ١٩٠٨؟",
     ["Frederick Cook", "Charles Wilkes", "Richard Byrd", "John Davis"],
     ["فريدريك كوك", "تشارلز ويلكس", "ريتشارد بيرد", "جون ديفيس"],
     "Cook said he reached the Pole one year before Peary. Both claims are doubted by historians today.",
     "قال كوك إنه وصل إلى القطب قبل بيري بسنة. وكلا الادعاءين موضع شك لدى المؤرخين اليوم."),
    (32, "medium",
     "Which explorer was the first to clearly fly over the South Pole, in 1929?",
     "أي مستكشف كان أول من حلّق بوضوح فوق القطب الجنوبي عام ١٩٢٩؟",
     ["Richard Byrd", "Roald Amundsen", "Charles Lindbergh", "Edmund Hillary"],
     ["ريتشارد بيرد", "روال أموندسن", "تشارلز ليندبيرغ", "إدموند هيلاري"],
     "American Richard Byrd flew over the South Pole on November 29, 1929, opening the age of polar aviation.",
     "حلّق الأمريكي ريتشارد بيرد فوق القطب الجنوبي في ٢٩ نوفمبر ١٩٢٩، فاتحًا عصر الطيران القطبي."),
    (33, "medium",
     "What kind of aircraft did Amundsen, Nobile and Ellsworth use over the North Pole in 1926?",
     "أي نوع من الطائرات استخدمه أموندسن ونوبيل وإلسوورث فوق القطب الشمالي عام ١٩٢٦؟",
     ["Airship Norge", "Hot air balloon", "Helicopter", "Glider"],
     ["المنطاد نورج", "منطاد هواء ساخن", "مروحية", "طائرة شراعية"],
     "The semi-rigid airship Norge crossed from Europe over the North Pole to Alaska — the first verified Pole reach.",
     "عبر المنطاد شبه الصلب نورج من أوروبا فوق القطب الشمالي إلى ألاسكا — أول وصول مؤكد للقطب."),
    (34, "medium",
     "What sad event happened to Amundsen on June 18, 1928?",
     "ماذا حدث لأموندسن في ١٨ يونيو ١٩٢٨ من حدث محزن؟",
     ["He disappeared in a rescue flight", "He was lost in a storm at sea", "He died of old age", "He gave up exploring"],
     ["اختفى في رحلة إنقاذ جوية", "ضاع في عاصفة في البحر", "مات من الشيخوخة", "تخلى عن الاستكشاف"],
     "Amundsen flew north to help find Italian explorer Umberto Nobile, whose airship Italia had crashed. Amundsen's plane vanished.",
     "طار أموندسن شمالًا للمساعدة في العثور على المستكشف الإيطالي أومبرتو نوبيل بعد تحطّم منطاده إيطاليا. اختفت طائرة أموندسن."),
    (35, "medium",
     "Which captain was the FIRST to cross the Antarctic Circle, in 1773?",
     "أي قبطان كان أول من عبر الدائرة القطبية الجنوبية عام ١٧٧٣؟",
     ["Captain James Cook", "Captain John Davis", "Captain Robert Scott", "Captain Edward Bransfield"],
     ["الكابتن جيمس كوك", "الكابتن جون ديفيس", "الكابتن روبرت سكوت", "الكابتن إدوارد برانسفيلد"],
     "British navigator Captain James Cook crossed the Antarctic Circle on January 17, 1773.",
     "عبر الملّاح البريطاني الكابتن جيمس كوك الدائرة القطبية الجنوبية في ١٧ يناير ١٧٧٣."),
    (36, "medium",
     "Which country sent Bellingshausen and Lazarev, who likely first SAW the Antarctic continent in 1820?",
     "أي بلد أرسل بيلينغسهاوزن ولازاريف، اللذين رأيا أول مرة على الأرجح القارة القطبية الجنوبية عام ١٨٢٠؟",
     ["Russia", "France", "Spain", "Germany"],
     ["روسيا", "فرنسا", "إسبانيا", "ألمانيا"],
     "On January 27, 1820 Russian sailors Fabian Bellingshausen and Mikhail Lazarev sighted the icy coast.",
     "في ٢٧ يناير ١٨٢٠ شاهد البحاران الروسيان فابيان بيلينغسهاوزن وميخائيل لازاريف الساحل الجليدي."),
    (37, "medium",
     "Who is said to have first LANDED on the Antarctic continent in 1821?",
     "من يُقال إنه أول من نزل على أرض القارة القطبية الجنوبية عام ١٨٢١؟",
     ["John Davis (US sealer)", "James Cook", "Edmund Hillary", "Otto Sverdrup"],
     ["جون ديفيس (صيّاد الفقمة الأمريكي)", "جيمس كوك", "إدموند هيلاري", "أوتو سفيردروب"],
     "American sealer John Davis is said to have stepped ashore on February 7, 1821 — the first known landing.",
     "يُقال إن صيّاد الفقمة الأمريكي جون ديفيس نزل إلى الشاطئ في ٧ فبراير ١٨٢١ — أول هبوط معروف."),
    (38, "medium",
     "Whose 1839-43 British expedition explored the Ross Sea and Ross Ice Shelf?",
     "بعثة من البريطانية بين عامي ١٨٣٩ و ١٨٤٣ استكشفت بحر روس وجرف روس الجليدي؟",
     ["James Clark Ross", "Charles Wilkes", "Captain Cook", "Adrien de Gerlache"],
     ["جيمس كلارك روس", "تشارلز ويلكس", "الكابتن كوك", "أدريان دي جيرلاش"],
     "James Clark Ross's expedition mapped huge new areas — the Ross Sea and Ross Ice Shelf are named after him.",
     "رسمت بعثة جيمس كلارك روس مساحات شاسعة جديدة — وقد سُميت بحر روس وجرف روس الجليدي باسمه."),
    (39, "medium",
     "How close did Shackleton get to the South Pole on his 1907-09 'Nimrod' expedition?",
     "كم اقترب شاكلتون من القطب الجنوبي في بعثته 'نيمرود' بين عامي ١٩٠٧ و ١٩٠٩؟",
     ["About 97 miles", "About 500 miles", "He reached it", "About 1 mile"],
     ["نحو ٩٧ ميلًا", "نحو ٥٠٠ ميل", "وصل إليه", "نحو ميل واحد"],
     "Shackleton turned back at 88°23'S — only ~97 miles short — to save his hungry team. A brave decision.",
     "تراجع شاكلتون عند خط العرض ٨٨°٢٣' جنوبًا — على بُعد نحو ٩٧ ميلًا فقط — لإنقاذ فريقه الجائع. قرار شجاع."),
    (40, "medium",
     "Which book by Apsley Cherry-Garrard tells about a tough emperor penguin egg trip?",
     "أي كتاب لأبسلي شيري غارارد يحكي عن رحلة قاسية لجلب بيض البطريق الإمبراطور؟",
     ["The Worst Journey in the World", "Around the World in 80 Days", "Treasure Island", "Endurance"],
     ["أسوأ رحلة في العالم", "حول العالم في ٨٠ يومًا", "جزيرة الكنز", "إندورانس"],
     "Cherry-Garrard's 1922 classic describes a brutal winter trek to Cape Crozier to study emperor penguin eggs.",
     "يصف كتاب شيري غارارد الكلاسيكي عام ١٩٢٢ رحلة شتوية قاسية إلى كيب كروزير لدراسة بيض البطريق الإمبراطور."),
    (41, "medium",
     "Who was the first person to spend an entire winter on the Antarctic continent (1899)?",
     "من أول شخص أمضى شتاءً كاملًا على أرض القارة القطبية الجنوبية عام ١٨٩٩؟",
     ["Carsten Borchgrevink", "Robert Scott", "Roald Amundsen", "Richard Byrd"],
     ["كارستن بورخغرفينك", "روبرت سكوت", "روال أموندسن", "ريتشارد بيرد"],
     "Norwegian-British Borchgrevink and his team spent the winter at Cape Adare — a first on the continent.",
     "أمضى النرويجي البريطاني بورخغرفينك وفريقه الشتاء في كيب أداري — وكان ذلك أول حدث من نوعه على القارة."),
    (42, "medium",
     "Which 1897-99 expedition got TRAPPED in the ice and was first to overwinter in Antarctic waters?",
     "أي بعثة بين عامي ١٨٩٧ و ١٨٩٩ حُوصرت في الجليد وكانت أول من قضى الشتاء في مياه القارة القطبية الجنوبية؟",
     ["Belgian Antarctic Expedition (Belgica)", "Endurance Expedition", "Discovery Expedition", "Terra Nova Expedition"],
     ["البعثة البلجيكية للقارة القطبية الجنوبية (بلجيكا)", "بعثة إندورانس", "بعثة ديسكفري", "بعثة تيرّا نوفا"],
     "The ship Belgica got stuck — and a young Norwegian named Roald Amundsen learned a lot as her mate!",
     "علقت السفينة بلجيكا — وتعلّم شاب نرويجي يُدعى روال أموندسن الكثير وهو يعمل ضابطًا فيها!"),
    (43, "medium",
     "Which Norwegian let his ship Fram drift with the Arctic ice in 1893-96?",
     "أي نرويجي ترك سفينته فرام تنجرف مع جليد القطب الشمالي بين عامي ١٨٩٣ و ١٨٩٦؟",
     ["Fridtjof Nansen", "Otto Sverdrup", "Roald Amundsen", "Carsten Borchgrevink"],
     ["فريدتيوف نانسن", "أوتو سفيردروب", "روال أموندسن", "كارستن بورخغرفينك"],
     "Nansen's idea was to freeze the strong ship Fram into the ice and let currents carry it across the Arctic.",
     "كانت فكرة نانسن أن تتجمد السفينة المتينة فرام في الجليد وتدعها التيارات تحملها عبر القطب الشمالي."),
    (44, "medium",
     "Who first sailed all the way through the Northwest Passage (1903-06)?",
     "من أول من أبحر عبر الممر الشمالي الغربي بأكمله بين عامي ١٩٠٣ و ١٩٠٦؟",
     ["Roald Amundsen (in Gjøa)", "Henry Hudson", "Captain Cook", "Christopher Columbus"],
     ["روال أموندسن (في غيوا)", "هنري هدسون", "الكابتن كوك", "كريستوفر كولومبوس"],
     "Amundsen and 6 crewmen took the small ship Gjøa through the icy passage — a 3-year journey.",
     "أخذ أموندسن و ٦ من بحارته السفينة الصغيرة غيوا عبر الممر الجليدي — في رحلة استغرقت ٣ سنوات."),
    (45, "medium",
     "Which expedition (1955-58) made the first overland CROSSING of all of Antarctica?",
     "أي بعثة بين عامي ١٩٥٥ و ١٩٥٨ قامت بأول عبور بري للقارة القطبية الجنوبية بأكملها؟",
     ["British Trans-Antarctic Expedition (Fuchs and Hillary)", "Nimrod expedition", "Belgica expedition", "Discovery expedition"],
     ["البعثة البريطانية عبر القارة القطبية الجنوبية (فوكس وهيلاري)", "بعثة نيمرود", "بعثة بلجيكا", "بعثة ديسكفري"],
     "Vivian Fuchs led the crossing while Edmund Hillary supported from the New Zealand side.",
     "قاد فيفيان فوكس عملية العبور بينما ساند إدموند هيلاري من الجانب النيوزيلندي."),
    (46, "medium",
     "What FAMOUS thing did Roald Amundsen also lead, before the South Pole?",
     "ما الإنجاز الشهير الآخر الذي قاده روال أموندسن قبل القطب الجنوبي؟",
     ["First crossing of the Northwest Passage", "First flight to the Moon", "First Mount Everest climb", "First trip to Mars"],
     ["أول عبور للممر الشمالي الغربي", "أول رحلة إلى القمر", "أول تسلق لجبل إفرست", "أول رحلة إلى المريخ"],
     "Before the South Pole, Amundsen had already become the first to sail through the Northwest Passage.",
     "قبل القطب الجنوبي، كان أموندسن قد أصبح بالفعل أول من أبحر عبر الممر الشمالي الغربي."),

    # ---- HARD (14) ----
    (47, "hard",
     "What were Robert Falcon Scott's last words written in his diary?",
     "ما الكلمات الأخيرة التي كتبها روبرت فالكون سكوت في يومياته؟",
     ["For God's sake look after our people", "I will return soon", "Antarctica is beautiful", "We have failed"],
     ["بحق الله اعتنوا بأهلنا", "سأعود قريبًا", "القارة القطبية الجنوبية جميلة", "لقد فشلنا"],
     "Scott's diary, found beside his frozen body, ended with this plea for the families of his men.",
     "انتهت يوميات سكوت، التي وُجدت بجانب جثته المتجمدة، بهذا الرجاء من أجل عائلات رجاله."),
    (48, "hard",
     "Roughly how many men were on the Endurance — and how many died in the ice?",
     "كم رجلًا تقريبًا كان على متن إندورانس — وكم مات منهم في الجليد؟",
     ["28 men, 0 died", "28 men, 10 died", "12 men, 5 died", "60 men, 30 died"],
     ["٢٨ رجلًا، مات ٠", "٢٨ رجلًا، مات ١٠", "١٢ رجلًا، مات ٥", "٦٠ رجلًا، مات ٣٠"],
     "Every single one of Shackleton's 28 men survived — one of the most amazing rescues in history.",
     "نجا كل واحد من رجال شاكلتون الـ ٢٨ — وهي من أعجب عمليات الإنقاذ في التاريخ."),
    (49, "hard",
     "What is the LOWEST natural temperature ever recorded on Earth?",
     "ما أدنى درجة حرارة طبيعية سُجِّلت في الأرض؟",
     ["About -89°C at Vostok, 1983", "About -50°C at the South Pole", "About -100°C in Greenland", "About -30°C in Siberia"],
     ["نحو ٨٩°- مئوية في فوستوك عام ١٩٨٣", "نحو ٥٠°- مئوية في القطب الجنوبي", "نحو ١٠٠°- مئوية في جرينلاند", "نحو ٣٠°- مئوية في سيبيريا"],
     "On July 21, 1983 the Russian Vostok Station in Antarctica recorded -89.2°C — the coldest ever.",
     "في ٢١ يوليو ١٩٨٣ سجّلت محطة فوستوك الروسية في القارة القطبية الجنوبية ٨٩٫٢°- مئوية — وهي الأبرد على الإطلاق."),
    (50, "hard",
     "When was the Antarctic Treaty signed, protecting the continent for science?",
     "متى وُقّعت معاهدة أنتاركتيكا، التي تحمي القارة من أجل العلم؟",
     ["December 1, 1959", "January 17, 1773", "April 6, 1909", "November 29, 1929"],
     ["١ ديسمبر ١٩٥٩", "١٧ يناير ١٧٧٣", "٦ أبريل ١٩٠٩", "٢٩ نوفمبر ١٩٢٩"],
     "12 countries signed in 1959; the treaty came into force in 1961 and now has about 54 members.",
     "وقّعت عليها ١٢ دولة عام ١٩٥٩؛ ودخلت المعاهدة حيز التنفيذ عام ١٩٦١، وفيها اليوم نحو ٥٤ دولة عضوًا."),
    (51, "hard",
     "Which Antarctic station sits exactly at the South Pole?",
     "أي محطة في القارة القطبية الجنوبية تقع تمامًا عند القطب الجنوبي؟",
     ["Amundsen-Scott Station (US)", "McMurdo Station (US)", "Vostok Station (Russia)", "Halley Station (UK)"],
     ["محطة أموندسن-سكوت (أمريكية)", "محطة ماكمردو (أمريكية)", "محطة فوستوك (روسية)", "محطة هالي (بريطانية)"],
     "Amundsen-Scott Station, opened in 1956, is named after the two explorers who reached the Pole first.",
     "محطة أموندسن-سكوت، التي افتُتحت عام ١٩٥٦، سُميت تيمنًا بالمستكشفَين اللذَين وصلا إلى القطب أولًا."),
    (52, "hard",
     "Which UK station detected the Antarctic ozone hole in 1985?",
     "أي محطة بريطانية اكتشفت ثقب الأوزون فوق القارة القطبية الجنوبية عام ١٩٨٥؟",
     ["Halley Research Station", "McMurdo Station", "Vostok Station", "Amundsen-Scott Station"],
     ["محطة هالي للأبحاث", "محطة ماكمردو", "محطة فوستوك", "محطة أموندسن-سكوت"],
     "British scientist Joe Farman and team at Halley spotted that ozone was thinning fast above Antarctica.",
     "اكتشف العالم البريطاني جو فارمان وفريقه في هالي أن طبقة الأوزون تترقّق بسرعة فوق القارة القطبية الجنوبية."),
    (53, "hard",
     "What is Lake Vostok?",
     "ما هي بحيرة فوستوك؟",
     ["A huge lake hidden under 4 km of ice", "A salty lake in the desert", "A volcanic crater lake", "A frozen waterfall"],
     ["بحيرة ضخمة مخبأة تحت ٤ كم من الجليد", "بحيرة مالحة في الصحراء", "بحيرة في فوهة بركان", "شلال متجمد"],
     "Lake Vostok is a 'subglacial' lake — liquid water that has stayed sealed under Antarctic ice for millions of years.",
     "بحيرة فوستوك بحيرة 'تحت جليدية' — أي مياه سائلة بقيت محبوسة تحت الجليد لملايين السنين."),
    (54, "hard",
     "Which Antarctic ice shelf famously collapsed in 2002?",
     "أي جرف جليدي في القارة القطبية الجنوبية انهار بشكل مشهور عام ٢٠٠٢؟",
     ["Larsen B", "Ross Ice Shelf", "Filchner-Ronne", "Amery"],
     ["لارسن ب", "جرف روس الجليدي", "فيلشنر-روني", "أميري"],
     "In just a few weeks in 2002, the huge Larsen B ice shelf shattered into thousands of icebergs.",
     "في أسابيع قليلة فقط من عام ٢٠٠٢، تفتّت جرف لارسن ب الجليدي الضخم إلى آلاف الجبال الجليدية."),
    (55, "hard",
     "Which giant Antarctic glacier is nicknamed the 'Doomsday Glacier'?",
     "أي نهر جليدي عملاق في القارة القطبية الجنوبية يُلقّب بـ 'نهر يوم القيامة'؟",
     ["Thwaites Glacier", "Pine Island Glacier", "Beardmore Glacier", "Lambert Glacier"],
     ["نهر ثوايتس الجليدي", "نهر باين آيلاند الجليدي", "نهر بيردمور الجليدي", "نهر لامبرت الجليدي"],
     "If Thwaites melted fully, world sea levels could rise by more than half a meter — that's why scientists watch it closely.",
     "لو ذاب ثوايتس بالكامل، فقد يرتفع منسوب البحار في العالم بأكثر من نصف متر — لذلك يراقبه العلماء عن كثب."),
    (56, "hard",
     "Which TINY shrimp-like animal is the keystone food of Antarctica?",
     "أي حيوان صغير شبيه بالجمبري هو الغذاء الأساسي للقارة القطبية الجنوبية؟",
     ["Antarctic krill", "Lobster", "Octopus", "Sea cucumber"],
     ["كريل القطب الجنوبي", "الكركند", "الأخطبوط", "خيار البحر"],
     "Whales, seals, fish and penguins all eat krill — without it the whole Antarctic food chain would fall apart.",
     "تأكل الحيتان والفقمات والأسماك والبطاريق الكريل — وبدونه تنهار سلسلة غذاء القارة القطبية الجنوبية كلها."),
    (57, "hard",
     "Which dangerous body of water lies between Cape Horn and Antarctica?",
     "أي ممر مائي خطير يقع بين رأس هورن والقارة القطبية الجنوبية؟",
     ["Drake Passage", "Bering Strait", "English Channel", "Gulf of Aden"],
     ["ممر دريك", "مضيق بيرينغ", "القناة الإنجليزية", "خليج عدن"],
     "The Drake Passage has some of the wildest seas on Earth — even modern ships can have a rough crossing.",
     "ممر دريك من أعنف بحار الأرض — حتى السفن الحديثة قد تواجه عبورًا صعبًا فيه."),
    (58, "hard",
     "Which Danish-Greenlandic explorer studied Inuit life across the Arctic?",
     "أي مستكشف دنماركي-جرينلاندي درس حياة الإنويت في القطب الشمالي؟",
     ["Knud Rasmussen", "Otto Sverdrup", "Adrien de Gerlache", "Henry Hudson"],
     ["كنود راسموسن", "أوتو سفيردروب", "أدريان دي جيرلاش", "هنري هدسون"],
     "Rasmussen traveled by dog sled from Greenland to Alaska, recording Inuit stories and traditions.",
     "سافر راسموسن بزلاجة الكلاب من جرينلاند إلى ألاسكا، مدوّنًا قصص الإنويت وتقاليدهم."),
    (59, "hard",
     "Who first sailed the Northeast Passage (north of Russia) in 1879?",
     "من أبحر أول مرة عبر الممر الشمالي الشرقي (شمال روسيا) عام ١٨٧٩؟",
     ["Adolf Erik Nordenskiöld", "Roald Amundsen", "Henry Hudson", "James Cook"],
     ["أدولف إيريك نوردنشولد", "روال أموندسن", "هنري هدسون", "جيمس كوك"],
     "Finnish-Swedish explorer Nordenskiöld used his ship Vega to complete the icy route along Russia's north coast.",
     "استخدم المستكشف الفنلندي السويدي نوردنشولد سفينته فيجا لإكمال الطريق الجليدي على طول الساحل الروسي الشمالي."),
    (60, "hard",
     "What does the Greek word 'Arktos', root of 'Arctic', mean?",
     "ماذا تعني الكلمة اليونانية 'أركتوس'، أصل كلمة 'أركتيك'؟",
     ["Bear", "Cold", "Snow", "North star"],
     ["دب", "بارد", "ثلج", "نجم الشمال"],
     "'Arktos' means 'bear' — the constellation Ursa Major (the Great Bear) sits over the North Pole.",
     "'أركتوس' تعني 'دب' — كوكبة الدب الأكبر (أورسا ميجور) تقع فوق القطب الشمالي."),
]

assert len(RAW) == 60, f"need 60 items, got {len(RAW)}"

items = []
seen_en = set()
seen_ar = set()
for (n, diff, q_en, q_ar, opts_en, opts_ar, expl_en, expl_ar) in RAW:
    rid = f"ape_{n:03d}"
    # convert any stray Western digits in Arabic strings
    q_ar2 = ar(q_ar)
    opts_ar2 = [ar(x) for x in opts_ar]
    expl_ar2 = ar(expl_ar)
    item = {
        "id": rid,
        "type": "multiple_choice",
        "category": "history",
        "difficulty": diff,
        "question": q_en,
        "question_ar": q_ar2,
        "options": opts_en,
        "options_ar": opts_ar2,
        "correct_answer": opts_en[0],
        "correct_answer_ar": opts_ar2[0],
        "explanation": expl_en,
        "explanation_ar": expl_ar2,
        "image": "",
    }
    # checks
    assert len(opts_en) == 4 and len(set(opts_en)) == 4, rid + " EN opts not 4 distinct"
    assert len(opts_ar2) == 4 and len(set(opts_ar2)) == 4, rid + " AR opts not 4 distinct: " + str(opts_ar2)
    items.append(item)

# Difficulty count check
counts = {"easy": 0, "medium": 0, "hard": 0}
for it in items:
    counts[it["difficulty"]] += 1
assert counts == {"easy": 22, "medium": 24, "hard": 14}, counts

# Verify no Western digits anywhere in Arabic fields
WESTERN = re.compile(r"[0-9]")
for it in items:
    for f in ("question_ar", "explanation_ar", "correct_answer_ar"):
        assert not WESTERN.search(it[f]), f"{it['id']} {f} has Western digit: {it[f]!r}"
    for i, v in enumerate(it["options_ar"]):
        assert not WESTERN.search(v), f"{it['id']} options_ar[{i}] has Western digit: {v!r}"

OUT.parent.mkdir(parents=True, exist_ok=True)
# Write UTF-8 NO BOM
with OUT.open("w", encoding="utf-8", newline="\n") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)
    f.write("\n")

print(f"Wrote {OUT} with {len(items)} items, counts={counts}")
